### ISSUE TITLE
Text/Title/label below the QR code

### ISSUE THREAD

**Issue by delkant** [soldair/node-qrcode#112]
Is it possible to add some text at the bottom of the QR code?

**Comment by vigreco** [comment]
Hi @delkant, unfortunately this is not possible and I don't think it's something we'll going to implement as a built in feature.
A label is not really a part of qrcode symbols but is more a "style" related stuff.

Of course you could use HTML/CSS or any image manipulation lib to add your extra contents. Or, you could write your own custom renderer that also prints labels.

**Comment by delkant** [comment]
Thank you for the answer!. In my case I need this to provide stickers/labels to packages that we share with customers so we can track the status. And it is nice to have the related text representing the code when you are on a phone call with a customer (as a use case). Or just the related url when you use it for sharing websites.

I will take a look at the code and if I see I can add that feature I will create a PR.
