### ISSUE TITLE
terminal qrcode support resize

### ISSUE THREAD

**Issue by fragno** [soldair/node-qrcode#113]
qrcode 'http://www.example.com'
generate a qrcode in the terminal，but it is too large。can web support to resize the size？

qrcode 'http://www.example.com' --width 30 --height 30

is this possible？

**Comment by vigreco** [comment]
@fragno this is not possible.
The terminal renderer simply uses escape codes and `space` character to draw the symbol, so the final size depends on your terminal font.
Unfortunately there is no way to force a specific size since the output is not an image but only ASCII characters.

**Comment by FrankFan** [comment]
> @fragno this is not possible.
> The terminal renderer simply uses escape codes and `space` character to draw the symbol, so the final size depends on your terminal font.
> Unfortunately there is no way to force a specific size since the output is not an image but only ASCII characters.

how about this  ? https://github.com/soldair/node-qrcode/pull/233
