### ISSUE TITLE
how can i generate the same qrcode for a specific user with his username and password

### ISSUE THREAD

**Issue by zhaofeihao** [soldair/node-qrcode#115]
if i want generate a qrcode image base username and password for a user,how to config it?i'm a little confuse, thanks very very very much!

**Comment by vigreco** [comment]
Hi @zhaofeihao, you can put any text you want in a qrcode, so it's just a matter of choosing a format suitable for your use case.

I would avoid to put any sensible information in a qrcode though.
You could for example use an unique url with a random generated key that refers to a specific user. (It's just an idea, not really a solid solution)

```
https://mysite.com/login/a39fjk3l2blkfdl09a24nfu8
```

**Comment by zhaofeihao** [comment]
@vigreco thx~
