### ISSUE TITLE
QRCode with a URL 

### ISSUE THREAD

**Issue by soniurvashi11** [soldair/node-qrcode#116]
<img width="286" alt="screen shot 2018-01-21 at 7 52 18 pm" src="https://user-images.githubusercontent.com/10581743/35195123-a75916bc-fee4-11e7-9e80-d5c1deb65af3.png">

Is it possible to generate a QR code with the URL on top of it or I need to manually write into my html? Also.. how it will be possible to redirect to the specific URL as soon as user scan the QR code?

**Comment by vigreco** [comment]
Hi @soniurvashi11, you should use html to add the label. See #113.


> how it will be possible to redirect to the specific URL as soon as user scan the QR code?

Url redirection is not a feature of qr codes (which only contain the text) but belongs to qr code reader applications.
Some apps can automatically open the url if the user has enabled that option, but it's not something you can control through the qr code itself.

**Comment by Heshiyu1996** [comment]
thanks, @vigreco .
It works well when I set the "text" of qrcode with my redirect url.
