### ISSUE TITLE
Use crisp edge shape rendering for SVGs

### ISSUE THREAD

**Issue by nerdyman** [soldair/node-qrcode#118]
Hi,

I've noticed that generated SVGs can have blurred edges depending on their size. The `shape-rendering` attribute can prevent this as shown in the example below.

The left image is using default `shape-rendering`, the right is using `shape-rendering="crispEdges"`.

![qr-code-normal-vs-crisp](https://user-images.githubusercontent.com/4908432/35403002-255fbb42-01f6-11e8-982a-bf791469c160.png)

The attribute can be applied at the top level of the SVG element.

```SVG
<svg shape-rendering="crispEdges"><!-- contents --></svg>
```

[Live demo](https://codepen.io/nerdyman/pen/ypdReZ)

`optimizeSpeed` also produces similar results to `crispEdges`.

Is this something that could be added? I can also do a PR.

Thanks!

**Comment by soldair** [comment]
oh cool. it does look better. i would ping @vigreco to see what he thinks
