### ISSUE TITLE
It doesn't work in IE10 and lower.

### ISSUE THREAD

**Issue by roy-yi** [soldair/node-qrcode#121]
If I try `QRCode.toCanvas()` or `QRCode.toDataURL()` in IE 10, there is an error "

> Cannot read property 'getContext' of null

" in console.

How can I apply this in ≤IE10? Please help, thx.

**Comment by roy-yi** [comment]
Hi,
I found something weird.
In `brower.js` Line 28 & 43:
` else if (argsNum === 2 && !canvas.getContext) {
      opts = text
      text = canvas
      canvas = undefined
    }`
Here, my IE 10 will report `can't read property getContext of null or undefined`.
Then, I made this change:
` else if (argsNum === 2 && (!canvas || (canvas && !canvas.getContext))) {
      opts = text
      text = canvas
      canvas = undefined
    }`
After this, IE 10 reports `No Input Text`. 
I traced the code and found that canvas is undefined. How could it be this? Thx.


BTW, my code is as below
`let opts = {
          errorCorrectionLevel: 'H',
          type: 'image/png',
          width: 1000,
          rendererOpts: {
            quality: 0.3
          }
        };
`
`
QRCode.toDataURL('some text', opts)
  .then(qrUrl => {})
  .catch(err => {});`

Roy

**Comment by roy-yi** [comment]
Sorry, I finally found the reason. It was due to there is no window.location.origin in IE 10 & lower. This made the text undefined.

My fault . Sorry.

**Comment by soldair** [comment]
oh cool. glad you figured it out
