### ISSUE TITLE
Can we decode QR Code?

### ISSUE THREAD

**Issue by havinhthai** [soldair/node-qrcode#129]
## Version
react: 16.3.1
react-native: 0.55.4
node-qrcode: 1.2.0

## Issue
I'm using React Native and can I decode QR code from dataURL?

I don't see method to do that in documents.

Thank you.

**Comment by zixia** [comment]
+1 for decode support.

It would be sweet if we both support the server and the browser sides.

**Comment by soldair** [comment]
i would love to add a decoder.
if anyone is interested in taking this on i'm happy to review

**Comment by thankjava** [comment]
I am looking for this now, I think it is necessary as a common component of QR code, I hope you can add it.😄

**Comment by arjusmoon** [comment]
How to decode or read the QR code data ?

**Comment by xuliangzhan** [comment]
I hope you can add the API to read qr codes.

**Comment by soldair** [comment]
https://github.com/cozmo/jsQR looks like a great solution foir this. I'm going to start using it for the tests.

**Comment by developer239** [comment]
QR code library that doesn't decode QR code. 🤨
