### ISSUE TITLE
Why `data` cannot be empty string?

### ISSUE THREAD

**Issue by EcutDavid** [soldair/node-qrcode#130]
Hey, thanks for contributed this awesome lib!

A question about the parameter `data`, 
For what reason it cannot be an empty string?

https://github.com/soldair/node-qrcode/blob/df6434054564bbc0dc9877fae59e4dd0ea5d0444/lib/core/qrcode.js#L479-L481

Thanks!

**Comment by soldair** [comment]
i dont remember =)

**Comment by EcutDavid** [comment]
👍
