### ISSUE TITLE
Sizing the image/png QR code

### ISSUE THREAD

**Issue by lopezdp** [soldair/node-qrcode#133]
How do I adjust the size of the QR code to keep it visible on the screen. The larger the data that needs to be encoded the larger the QR code and right now it is taking up the entire screen and it is unscanable and I do not see a setting to allow me to change the size. I using it in a node application and passing the img data to the front end with AJAX...

**Comment by thankjava** [comment]
I have the same question.

**Comment by soldair** [comment]
you can reduce the error correction in the code to increase the data you can store but its just not practical to put too much data in a code for exactly the reason you said.
you just cant scan it if it's too big =)
