### ISSUE TITLE
Feature Inquiry 

### ISSUE THREAD

**Issue by RyanCookeYpb** [soldair/node-qrcode#136]
Hi there.

Great library.
I really like it and will keep using it in other future projects. 
I would just like to ask a couple of questions.

My use case requires me to be able to customize the colors of the top left, right and bottom left big main blocks.
If I wanted to be able to pass in three extra options to choose the colors what would the possibility of this?
And if its not possible or the contributes feel this feature is not necessary then would you be able to point me to the line of code where I would be able to implement this my self?

Thank you

**Comment by soldair** [comment]
if you grab a "bit array" you can draw the qrcode yourself with the drawing code or custom drawing code. take a peek its very neatly organized.
