### ISSUE TITLE
Accept color codes with only digits from the command line

### ISSUE THREAD

**Issue by abmaonline** [soldair/node-qrcode#137]
When running qrcode from the command line, it is not possible to provide color codes with only digits. 

When executing:
`qrcode -d 666 -o out.png "Hello!"`

This error is shown:
`Error: Color should be defined as hex string`

The check for a string seems to be the problem:
https://github.com/soldair/node-qrcode/blob/a3855cabaf37571729af59525c1ad81daee8743b/lib/renderer/utils.js#L1-L4

Since the color code only contains digits, it's turned into a number by js.

As a workaround a `#` can be added, but I had to look into the code to find that option:
`qrcode -d \#666 -o out.png "Hello!"`

Not sure if this should be fixed in the terminal code (cast both color codes to a string there), or if `hex2rgba` needs an extra check to convert a number to a string and then follow the rest of the logic, since there is a unit tests explicitly checking this:
https://github.com/soldair/node-qrcode/blob/a3855cabaf37571729af59525c1ad81daee8743b/test/unit/renderer/utils.test.js#L45-L46

qrcode: 1.2.1
node: 6.11.4
shell: zsh 5.4.2

**Comment by soldair** [comment]
this is reasonable i think. not sure how broadening the definition of color would cause an issue here.  happy to accept a pr.

**Comment by abmaonline** [comment]
👍 See #169
