### ISSUE TITLE
input base64 string to every generated qrcodes

### ISSUE THREAD

**Issue by Albert0405** [soldair/node-qrcode#139]
Could it be possible for each qrcode that i will create, it will also store a base64 string into it? I mean we can  access the string value of a qrcode in "data" how about a base64 string of the qrcode?

What i wanted to achieve is that, if i scan a qrcode, i would also like to display the scanned qrcode in my app especially if the qrcode has a logo in it....

**Comment by soldair** [comment]
im not sure i quite understand.
in order to scan it the scanner has to take a picture of the code.

**Comment by soldair** [comment]
i dont think it would be easy to make a code that only stores itself. :smile:
