### ISSUE TITLE
style width, height is in px

### ISSUE THREAD

**Issue by ghost** [soldair/node-qrcode#140]
At the moment i'm overriding the values, but it would be much more easier to scale, if you would set the style width and height to 100%.

```
<div class="something">
<canvas width="116" height="116" style="min-width:116px;min-height:116px;width:100vmin;height:100vmin"></canvas>
</div>
```
In this case the canvas size will be the outer div size. It's simpler. The attribute of width and height can remain what the qrcode module calculates.

vmin (called vm on ie9) means that it will be screen rotation resistant. I didn't even know about this feature of the browser, to be honest. Good to know. (reorganizing my whole css in my project :))

**Comment by soldair** [comment]
i'm not sure i know exactly what you mean but i would love to see a pr for this when ever you have a moment.
