### ISSUE TITLE
Bundle file not found

### ISSUE THREAD

**Issue by le4ker** [soldair/node-qrcode#141]
Hello,

I want to use the library without using Browserify and according to the documentation the library should exist in a file under a bundle folder, but I can't find it.

Let me know if my understanding was wrong.
If not, then adding the bundle file back to the repo would be great.

Cheers,
:panos

**Comment by soldair** [comment]
the bundle is never checked in but its published to the npm package. you can download a version tarball unpack it and pull the bundle from the build dir there.

curl https://registry.npmjs.org/qrcode/-/qrcode-1.2.0.tgz
