### ISSUE TITLE
Promise typing is wrong

### ISSUE THREAD

**Issue by jappyjan** [soldair/node-qrcode#143]
error  in /builds/JappyJan/GamePlay-V4/node_modules/qr-code-with-logo/types/index.d.ts

(36,50): Generic type 'Promise<T>' requires 1 type argument(s).

 error  in /builds/JappyJan/GamePlay-V4/node_modules/qr-code-with-logo/types/index.d.ts

(37,48): Generic type 'Promise<T>' requires 1 type argument(s).

**Comment by soldair** [comment]
this seems to be an issues with the typings file in qr-code-with-logo let me know if you solve it!

**Comment by jappyjan** [comment]
Needed to use this in production asap, so i've chosen another qr code generator instead.

Maybe I'll have a look at it in the future.
