### ISSUE TITLE
Impossible to run with parameters out of terminal

### ISSUE THREAD

**Issue by bluepioupiou** [soldair/node-qrcode#144]
Hi, I'm trying to launch qrcode from an ansible task and it fails systematically (returning the 'how to use').

I think I found the row that cause this. 

On row 122 if I change this

`if (process.stdin.isTTY) {`

to this

`if (process.stdin.isTTY || true) {`

I can use qrcode lib from an ansible task.

Is it a bug ? did I miss something ?
Thanks in advance

**Comment by soldair** [comment]
sounds like a bug because its doing something you dont expect. ill take a look.

**Comment by soldair** [comment]
what if you pipe the text to qr code?
`echo "my text" | npx qrcode`

**Comment by soldair** [comment]
i think that the bug is we should still look for text args even if we read from stdin.
especially if its empty

**Comment by soldair** [comment]
ok published version 1.2.2 should be fixed.

thanks for the report! this will help anyone executing the process outside an interactive terminal

**Comment by bluepioupiou** [comment]
Yeah ! Quick, complete and efficient. Thanks a lot
