### ISSUE TITLE
react-native: Error: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by straysh** [soldair/node-qrcode#147]
```
react-native-cli: 2.0.1
react-native: 0.55.4

"react-native-qrcode": "^0.2.7",
"react-native-qrcode-svg": "^5.1.0",
"react-native-svg": "^6.5.1",
```

project compiled success! But currupted at runtime as follow:
```
node_modules/qrcode/lib/utils/typedarray-buffer.js#L339
Buffer.prototype.slice = function slice (start, end) {
  ......
}
```
![image](https://user-images.githubusercontent.com/3816071/43635815-d6e677de-9742-11e8-9c5f-3263d95c9a9e.png)

-------------------------------------------------------------------
after change all `Buffer.slice` to `Buffer.slice2` (just change slice to something else), ALL worked!

-------------------------------------------------------------------
Updated:
found out that `Uint8Array.prototype.slice` is readonly, 
```
function createBuffer (that, length) {
  var buf
  if (Buffer.TYPED_ARRAY_SUPPORT) {
    buf = new Uint8Array(length)
    buf.__proto__ = Buffer.prototype
  } else {
    // Fallback: Return an object instance of the Buffer class
    buf = that
    if (buf === null) {
      buf = new Buffer(length)
    }
    buf.length = length
  }

  return buf
}
```
`createBuffer` return `Uint8Array` instance, so `Buffer.prototype.slice` not worked

**Comment by soldair** [comment]
interesting

**Comment by soldair** [comment]
curious what you found out that made you close the issue. maybe something i need to add to docs?
