### ISSUE TITLE
Separating CLI to its own module

### ISSUE THREAD

**Issue by shesek** [soldair/node-qrcode#149]
Would a pull request separating the CLI executable to its own package (`qrcode-cli`) be accepted?

I'm asking because I'd like to remove the dependency on `yargs`, which is responsible for ~90% of qrcode's dependencies size (2.26mb of 2.6mb).

**Comment by soldair** [comment]
im not super interested in this. its really important to uses to be able to `npx qrcode "im a teapot"` 
i am ok with a refactor to another argument parsing library like minimist etc and perhaps with moving the lib code out. i'd have to get feedback from other contributors though
