### ISSUE TITLE
[Feature Inquiry] Is it possible to create command keys? eg: ALT+CTRL+DEL

### ISSUE THREAD

**Issue by deanrather** [soldair/node-qrcode#154]
I'd love to use this to automate some of our support operations, removing the need for a keyboard entirely if possible.

But unless I can get the scanner to output the `alt+ctrl+del` key-press, we're still going to need a keyboard...

Is it possible?

**Comment by soldair** [comment]
this sounds like it would have to be a feature built into your scanner. those key presses don't generate characters so the reader would have to understand how to change some characters into key presses on the reading system. 

check out some desktop testing software for whatever operating system you're using.

**Comment by deanrather** [comment]
Thanks!
