### ISSUE TITLE
Invalid Data

### ISSUE THREAD

**Issue by steven87vt** [soldair/node-qrcode#155]
Good afternoon,

I just started using this library today, and am using v 1.3. I noticed it was released 3 days ago so I wanted to bring this up, I am getting an error when using toCanvas. Stepping through the code it seems like the argument list gets shuffled around and the function create (data, options) method is being feed the canvas parameter as data.

Please see the codesandbox link where I recreated the issue using a sample vue template:
[https://codesandbox.io/s/215wj71n0r](https://codesandbox.io/s/215wj71n0r)

```
<canvas id="canvas"></canvas >

....
'qrCode': function (val, oldVal) {
   if (val) {
       let canvas = document.getElementById('canvas');
       QRCode.toCanvas(canvas, val, function (error) { console.error(error) });
           document.getElementById('configTwoFactTitleSpinner').classList.remove("fa-spin");
       }
   }
....

..\..\some.vue:59 Error: Invalid data
    at createSymbol (qrcode.js:400)
    at Object.create (qrcode.js:498)
    at renderCanvas (browser.js:60)
    at VueComponent.qrCode (..\..\somevue:59)
    at Watcher.run (vue.js:3231)
    at flushSchedulerQueue (vue.js:2981)
    at Array.<anonymous> (vue.js:1839)
    at flushCallbacks (vue.js:1760)
```

**Comment by soldair** [comment]
thanks a lot for the report! ill take a look now

**Comment by soldair** [comment]
hey i found an un-closed canvas tag in your HelloWorld.vue.
Also i don't think there is any form of toCanvas that doesn't accept a canvas as an argument so the call pattern in the try catch is just the wrong args. should be canvas first.

https://codesandbox.io/s/pm71786900

I think this is working correctly. I'm going to close this for now but please respond with more information if you still find it behaving incorrectly. I could have totally misunderstood your report!

thank you

**Comment by steven87vt** [comment]
@Ryan

Yes that was a typo I made when I was messing around with it. I made a
mistake where I had supplied the canvas element as a div, which generates
the Invalid Data. Correcting to a canvas element fixes the issue, so it was
my fault. The other method works fine as well when you provide a callback
to append the canvas to a div.
