### ISSUE TITLE
Can't change color on QRCode.toDataURL()

### ISSUE THREAD

**Issue by jiyu3** [soldair/node-qrcode#158]
```
QRCode.toDataURL("Green is good color", (err, qr) => {
    console.log(qr)
})
```

It does work, but 

```
QRCode.toDataURL("Green is good color",  {color: { dark: "green", light: "white" } }, (err, qr) => {
    console.log(qr)
})
```

It does not work(nothing displayed).

How can I change color of qr code on QRCode.toDataURL() method?

**Comment by soldair** [comment]
looks like we only support hex colors
https://github.com/soldair/node-qrcode/blob/master/lib/renderer/utils.js#L1

have you tried '#1c8b25' for green and nothing for "light"?

**Comment by YashMarmat** [comment]
Thanks, it worked
Tried this:

`<canvas id="canvas${1}" style="margin:20px 5px 10px 5px;"></canvas> <script> QRCode.toDataURL(document.getElementById("canvas${1}"),"${<your_qr_url_here>}",{ color: { dark: "#fff", light: "#cc0403" }, width: 100, height: 100, margin: 0, }, function (error) { if (error) console.error(error); console.log("success!"); }); </script>`
