### ISSUE TITLE
how to implement a color qrcod 

### ISSUE THREAD

**Issue by xuqinggang** [soldair/node-qrcode#160]
![image](https://user-images.githubusercontent.com/13174560/48299518-ce649f00-e508-11e8-8f0d-c65ea1f50d83.png)
For example, the above picture. Can you give me some examples?

**Comment by soldair** [comment]
use qrcode.create to make an object with data in it.
https://github.com/soldair/node-qrcode#createtext-options

process the data with something like this to traform the bit array into r,g,b 
https://github.com/soldair/node-qrcode/blob/master/lib/renderer/utils.js#L67

and render it with png js maybe like we do here to get it as an image.
https://github.com/soldair/node-qrcode/blob/master/lib/renderer/png.js#L5

if you have an idea that might make this easier for people let me know =)
