### ISSUE TITLE
How to remove the default padding?

### ISSUE THREAD

**Issue by caiyichen** [soldair/node-qrcode#161]
```
QRCode.toDataURL('hello world', function (err, url) {
        this.qrcodeSrc = url;
})
```
```
<img :src="qrcodeSrc">
```
![wx20181113-151950](https://user-images.githubusercontent.com/22057677/48397102-a5861900-e757-11e8-9478-636246cad5bb.png)

Excuse me，how can I remove the default padding?

**Comment by nightire** [comment]
Use this option: https://github.com/soldair/node-qrcode#margin

**Comment by soldair** [comment]
yeah great answer @nightire =)

```
QRCode.toDataURL('hello world',{margin:0}, function (err, url) {
        this.qrcodeSrc = url;
})
```

**Comment by adamreisnz** [comment]
I've used margin: 0 and there's still a ton of padding. Is margin ignored when using custom width?
