### ISSUE TITLE
qrcode__WEBPACK_IMPORTED_MODULE_7__.toFile is not a function

### ISSUE THREAD

**Issue by osterland** [soldair/node-qrcode#162]
I do get the following error, when ever i try to save my qr as a file:
qrcode__WEBPACK_IMPORTED_MODULE_7__.toFile is not a function

The rest ( toCanvas, .. ) is working as expected. :) 

any ideas what i do wrong? 

Version:    "qrcode": "^1.3.2",
 
regards, 

Kevin

**Comment by soldair** [comment]
not sure. it looks like you're using a webpacked version of qrcode on the server but we dont use webpack to bundle this project.

could you be using something like @zeit/ncc to bundle server code? 
if you give me a small example of how you're requireing the lib im happy to take a look
