### ISSUE TITLE
Snyk reporting a vulnerability issue with yargs@8.0.2

### ISSUE THREAD

**Issue by Fetz** [soldair/node-qrcode#163]
I don't know how much risky or valid this issue for this module, but would be good to upgrade yargs

> **Denial of Service (DoS)**
> Vulnerable module: mem
> Introduced through: yargs@8.0.2
> Detailed paths
> Introduced through: qrcode@1.3.2 › yargs@8.0.2 › os-locale@2.1.0 › mem@1.1.0
> Remediation: Upgrade to yargs@12.0.2.
> Overview
> mem is an optimization technique used to speed up consecutive function calls by caching the result of calls with identical input.

> Affected versions of this package are vulnerable to Denial of Service (DoS) attacks. Old results are not deleted from the cache and could cause a memory leak.

> [more details](https://app.snyk.io/vuln/npm:mem:20180117)

**Comment by soldair** [comment]
thanks for the heads up.

**Comment by Fetz** [comment]
thanks a lot
