### ISSUE TITLE
Maintain a changelog

### ISSUE THREAD

**Issue by MartinMuzatko** [soldair/node-qrcode#165]
Hello!

I'm updating my dependencies - are there any breaking changes between 0.x.x and 1.x.x? Otherwise there wouldn't be a breaking change.

If you don't want the overhead of maintaining a changelog, you should at least document breaking changes and migration paths.

**Comment by soldair** [comment]
i'll take a look at conventional commits and conventional changelog thanks for the suggestion :smile: 

there are no breaking changes to version 1.0. the package has been pretty stable as far as api goes through multiple refactors and its time to promote it from pre-release 0 (where semver doesn't necessarily apply) to 1

**Comment by mqklin** [comment]
@soldair is there still no changes? I want to upgrade to 1.4.2 from 1.4.1
