### ISSUE TITLE
Example for writing qr code image to response in express

### ISSUE THREAD

**Issue by koder217** [soldair/node-qrcode#168]
```
const qr = require('qrcode'),
module.exports.getQrImage = function (req, res) {
qr.toFileStream(res, "Hello QR");
}
```

The above code is not working in any browser. Not sure what I am doing wrong. Help?

**Comment by soldair** [comment]
rather curious. based on the api docs for this function it should work. let me know if you figure it out

**Comment by soldair** [comment]
the below example works great. maybe you need to set the correct content type.
```
let qrcode = require('qrcode')
let http = require('http')

let server = http.createServer((req,res)=>{
  res.setHeader('content-type','image/png');
  qrcode.toFileStream(res, "Hello QR");
})

server.listen(8080,()=>console.log('listening')) 
```

**Comment by fhirfly** [comment]
tying to run this in Lambda, throws the error:

 {"errorType":"TypeError","errorMessage":"Cannot read property 'bind' of undefined","trace":["TypeError: Cannot read property 'bind' of undefined","    at Object.toFileStream (/var/task/node_modules/qrcode/lib/server.js:133:52)","    at Runtime.module.exports.getCertificateQRCode [as handler] (/var/task/handler.js:40:11)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}

` 
 module.exports.getCertificateQRCode = async (event) => {     
   const response = {headers: {"content-type": "image/png"},};
   qrcode.toFileStream(response, "whateverstring");
   return response;
 };`

I did confirm your code works in a simple http server.
