### ISSUE TITLE
Setting border width (quiet zone?) in toDataUrl()

### ISSUE THREAD

**Issue by owl-93** [soldair/node-qrcode#171]
Is there a way to set the border/quiet zone of generated QR via options using the toDataUrl() function in client side? I'm generating the image as base64 encoded png

for example, I'm trying to accomplish this using an options parameter something like:
```
{
    color: {
        dark: color,
        light: color !== '#FFFFFF' ? '#FFFFFF' : '#000000'
    },
    renderer: {
        quietZone: '0px'
    }
}
```

**Comment by soldair** [comment]
https://github.com/soldair/node-qrcode#renderers-options
i think you want to set margin: 0

**Comment by owl-93** [comment]
Thanks yes thats what I was looking for
