### ISSUE TITLE
UTF-8 Characters not read with ZBar

### ISSUE THREAD

**Issue by PupRenaud** [soldair/node-qrcode#172]
Hello,
UTF-8 characters such as 'é' could not be read with ZBar.
After a lot of work I managed to add UTF-8 BOM before passing the String to node-qrcode and bingo, it is working.

I suggest you add this tweak into your manual to help further developers.

````javascript
var textBuffer = new Buffer(text, 'utf8')
var utf8BomBuffer = Buffer(3)
utf8BomBuffer[0] = 0xef
utf8BomBuffer[1] = 0xbb
utf8BomBuffer[2] = 0xbf
var finalBuffer = Buffer.concat([utf8BomBuffer, textBuffer])
QRCode.toCanvas(this.$refs.qrCodeCanvas, finalBuffer.toString())
````

**Comment by soldair** [comment]
interesting. so you're getting invalid utf8 as input? nice fix.
i'm not sure how to make this generic. 
maybe folks should process input with https://www.npmjs.com/package/utf8? or make a helper to fix the bom. 

the format of data you put into the library is generally out of scope it can only encode what you pass.
thanks for the suggestion. if you think of a way to document this  or a reduced test case i would happily accept a pr

**Comment by PupRenaud** [comment]
I juste tried your suggestion. It is not working at all.
````javascript
QRCode.toCanvas(this.$refs.qrCodeCanvas, utf8.encode(text))
````
I am reading the internet and everybody is very confused about what is encoding. But in fact it is should be a very simple matter. I have been working a lot with filesystems in Java and we share the same logic.
Usually you should be concerned about encoding only when doing byte[] <-> string conversions.
When working inside javascript, you should not be concerned about encoding at all.
So in my case, the `text` is read from the input of the user in the inputText field. I think it is reasonable to trust that this component is nicely coded and tested.  

So my guess is there is an issue with the output string -> byte[] conversion. When I look at your code I see this 
````javascript
exports.render = function render (qrData, options, cb) {
  var opts = Utils.getOptions(options)
  var size = qrData.modules.size
  var data = qrData.modules.data
  var qrcodesize = size + opts.margin * 2
````
You are using the string array "as is" but the default encoding is unknown and is not absolute because depending on the user locale or javascript environment.
In java they totally removed the ability to access the byte[] under the string without and explicit encoding. 

So I think you should not do the string -> byte[] conversion by yourself without and explicit encoding.
You should either ask the user to provide a byte[] array, or at least to provide the wanted encoding. And if you have to default, you should default to 'UTF-8' which is the international standard.

**Comment by soldair** [comment]
Seems like you're on track. I am very sure this library should not take on complexity like encoding. Especially if you're in a browser because you can set any encoding you like as a meta tag or header serving the html.

This works for chinese and other encodings without changes so I'm sure there is a better way to approach this.

**Comment by PupRenaud** [comment]
Hi @soldair , as long as you are "encoding" a String inside a QRCode, you have to assume the "encoder" role ! There is something wrong if your encoding process is locale-dependant which is the case if you don't specify the encoding before turning String into Byte[].
I think the problem is the QRCode standard which don't provide a standard way of providing the decoding hand with a header about which "encoding" should be assumed.
I think most QRCode reader are trying to "guess" the encoding directly by analyzing the content. This is why adding the BOM is helping in my case.
Anyway thank you for sharing your work, this is already fantastic and doing the job for me !
