### ISSUE TITLE
QRCode.toDataURL on react-native asking for canvas

### ISSUE THREAD

**Issue by Kinark** [soldair/node-qrcode#175]
Maybe this is a duplicate of #75, but I really need the dataURL to save a file and send it by e-mail.

When I call the `toDataURL` in react-native it seems that the lib understands that I'm in a browser environment and calls for a canvas element. So this:

```
QRCode.toDataURL(undefined, 'some content 123456').then(async base64QrPng => {
}).catch(err => console.log(err))
```

Throws this error:

```
You need to specify a canvas element
- node_modules\qrcode\lib\renderer\canvas.js:17:20 in getCanvasElement
...
```

Is there any workaround for this problem?

**Comment by soldair** [comment]
so. we worked around this before in that other issue by rendering to an svg instead of a png.
the only choices are you can make your own renderer, use svg, or add a canvas object to react-native.

```js
...
let svg = await a.toString('apples',{type:'svg'})
console.log(svg)
```
hope this helps.

if you have a nice way to test react-native and qrcode its something we might like to make easier to support.

please feel free to reopen this issue if you have any feedback or think i missed the question.

**Comment by KingAmo** [comment]
if there is a `api` like `QRCode.toBase64()`, then we can use it in React Native like this:
```
import { Image } from 'react-native;
...
const base64img = QRCode.toBase64('hello world')
 ...

<Image source={{uri: base64img}} />
```

**Comment by KingAmo** [comment]
in fact i found https://www.npmjs.com/package/qrcode-generator 's `createDataURL` return a `base64` string that is exactly we need in `react-native`

**Comment by Jorundur** [comment]
@soldair I second this - it would be great to get something similar to `toBase64()` like @KingAmo mentioned above. Using https://www.npmjs.com/package/qrcode-generator is a good idea but unfortunately it lacks a lot of other features that `node-qrcode` has, e.g. changing the colors and more.

**Comment by soldair** [comment]
Base 64 encoding is built into nodes Buffer. It might be tricky to port in a cross runtime way though. Once you have a png you just say toString('base64') and put data:image/png, before it

**Comment by markw13a** [comment]
I think the trouble is that there's no way to generate a png in the first place if Canvas is not available -- as is the case for React Native.

It looks as though the only way to make use of this library with React Native is to generate SVGs. React Native does not support SVGs out-of-the-box so you then need to add something like react-native-svg to your project.
