### ISSUE TITLE
REQUEST FOR INFO: Reader options for Nativescript compatible with Node-qrcode

### ISSUE THREAD

**Issue by hashoshi** [soldair/node-qrcode#177]
I am using the Nativescript QR code reader library and it has an array of options for preferred encoding patterns. Supported types: CODE_128, CODE_39, CODE_93, CODABAR, DATA_MATRIX, EAN_13, EAN_8, ITF, QR_CODE, UPC_A, UPC_E, PDF417, AZTEC.

Which is best (if any) for the QR codes created with this QR code generator library? I am creating the QR's on auto mode, so maybe the safest bet is to use Auto on the reader as well?

Just want to make sure I'm using the optimal settings. Thank you in advance!

**Comment by soldair** [comment]
It's definitely a QR_CODE. it's one of the types you sent.  This library will only make qrcodes.
I have never used the code reader you're using but you probably want to set it to auto if you want to read any other types of codes but if its only qr codes qr_code is likely ok.
