### ISSUE TITLE
Add Image Inside of QRcode?

### ISSUE THREAD

**Issue by Craig-Burch** [soldair/node-qrcode#182]
I have figured out how to customize colors of a QRcode

let url = await QRCode.toDataURL(new_card.data, {
               color: {
               dark: '#000000',  // black dots
                light: '#ffffff' // white background
            }
        })

Can I add images as well to the QRcode?
Say I wanted to place my companies logo right in the middle of the QRcode...
Thanks!

**Comment by Craig-Burch** [comment]
I may have to use another package but this may be able to work..
https://ourcodeworld.com/articles/read/419/how-to-merge-an-image-into-a-qr-code-in-javascript

**Comment by soldair** [comment]
it's pretty easy. you create the canvas object and write an image to coordinates you want
with pngjs i'm not as sure but this doesnt do it for you out of box.

**Comment by Craig-Burch** [comment]
Thank you @soldair ! I was using the Qart package yesterday and it hasn't been maintained in 2 years! It hurt to use. I will check out pngjs. Thanks again!

**Comment by taoqf** [comment]
Is it able to add image to the center of the qrcode, even with qartjs?

**Comment by Craig-Burch** [comment]
Qart isn't maintained nowadays I would tread carefully there.
i used a canvas to add an image onto my qrcodes.

    <img 
     id="logoBlack" 
     src="img/iconBlack.png"
     style="display: none;"
    >
    <canvas 
      id="QRcanvas" 
      width="400" 
      height="400" 
      style="display: none;">
    </canvas>


 async createQRblack() {
      //grab data you want on qrcode here
       try { 
        let dataForQRcode = await axios.post("Your/Vcard/Route", data)
       //post above will send to a route that returns Vcard data to front end
        let url = await QRCode.toCanvas(dataForQRcode , {  
              errorCorrectionLevel: 'Q',
               margin: 1,
               color: {
                 dark:  '#000000',  // black pixels
                 light: '#ffffff', // white background
               }
            })
            var canvas = document.getElementById("QRcanvas");
            var ctx = canvas.getContext("2d");
            var img = document.getElementById("logoBlack");
            ctx.drawImage(url, 30, 30, 325, 325); 
            ctx.drawImage(img, 143, 143, 100, 100);     
            var download = document.createElement('a');
            download.href = canvas.toDataURL("image/png") 
            download.download = this.data.nameYouWantForFile;
            download.click();
         }
       }  catch (e) {
          console.log(`vcard error / Front end =`, e);
      } 
    },

**Comment by taoqf** [comment]
@Craig-Burch Thanks, I should try.

**Comment by taoqf** [comment]
Thank you very much. I did it on server side, below is my code.

```js
const QRCode = require('qrcode');
const { createCanvas, loadImage } = require('canvas');

async function create_qrcode(dataForQRcode, center_image, width, cwidth) {
	// grab data you want on qrcode here
	const cvs = createCanvas(1, 1);
	const url = await QRCode.toCanvas(cvs, dataForQRcode, {
		errorCorrectionLevel: 'H',	// LMQH
		margin: 1,
		color: {
			dark: '#000000',	// black pixels
			light: '#ffffff',	// white background
		}
	});
	const canvas = createCanvas(width, width);
	const ctx = canvas.getContext("2d");
	const img = await loadImage(center_image);
	ctx.drawImage(url, 0, 0, 108, 108, 0, 0, width, width);
	const center = (width - cwidth) / 2;
	ctx.drawImage(img, center, center, cwidth, cwidth);
	return canvas.toDataURL("image/png");
}
```

**Comment by Craig-Burch** [comment]
awesome @taoqf  ! Looks great, well done!

**Comment by amarjeet045** [comment]
@taoqf  when i have used your code it doesn't work properly can you suggest any solution here is the image of the rendered qr code with image on the center 
![Screenshot from 2020-11-20 16-06-42](https://user-images.githubusercontent.com/33446077/99790752-8ee6d980-2b4a-11eb-959c-3a616c0c6c1d.png)

and here i am trying to pass in the function 

create_qrcode(
  "http://shauryamuttreja.com/qr/id=123456",
  "https://firebasestorage.googleapis.com/v0/b/growthfilepractice.appspot.com/o/Logo.png?alt=media&token=209b47f8-d10b-454d-bbfe-627c9a43da0a",
  100,
  100
);

**Comment by taoqf** [comment]
@amarjeet045 You should fetch the image first, then draw it.

**Comment by amarjeet045** [comment]
I have made the image in the middle of the qr code but it doesn't show proper on mobile i have used svg and png images as logo but it doesn't show properly.

**Comment by techinoviq9000** [comment]
This code will save the qr code as png on your disk. Nodejs code

```
const QRCode = require("qrcode");
const fs = require("fs");
const { createCanvas, loadImage } = require("canvas");

async function create(dataForQRcode, center_image, width, cwidth) {
  const canvas = createCanvas(width, width);
  await QRCode.toCanvas(
    canvas,
    dataForQRcode,
    {
      errorCorrectionLevel: "H",
      margin: 1,
      width: 500,
      color: {
        dark: "#000000",
        light: "#ffffff",
      },
    }
  );

  const ctx = canvas.getContext("2d");
  
  // Load the image
  const img = await loadImage(center_image);
  console.log("Image:", img); // Check the image object
  
  // Draw the image onto the canvas
  const center = (width - cwidth) / 2;
  ctx.drawImage(img, center, center, cwidth, cwidth);
  
  // Return the data URL
  return canvas.toDataURL("image/png");
}
function saveBase64ToPNG(base64String, fileName) {
  // Strip the metadata from the base64 string
  const base64Data = base64String.replace(/^data:image\/png;base64,/, "");

  // Decode the base64 string into a buffer
  const buffer = Buffer.from(base64Data, "base64");

  // Write the buffer to a file
  fs.writeFileSync(fileName, buffer);

  console.log(`Saved ${fileName}`);
}
async function main() {
  const qrCode = await create(
    "your url,
    './icon.png', //any image
    500,
    100
  );
  const fileName = "output.png";
  saveBase64ToPNG(qrCode, fileName);
}

main();
```
