### ISSUE TITLE
Leading Zero is omitted

### ISSUE THREAD

**Issue by BernhardFuchs** [soldair/node-qrcode#184]
**Steps to Reproduce:**
- create a code with a leading zero e.g. 0123 or "0123"

**Actual:**
- the zero is omitted and the output is 123

**Expected:**
- output should be 0123 in both cases

**Comment by soldair** [comment]
interesting :thinking:  ill check it out

**Comment by soldair** [comment]
fixed. release in 1.3,.4.
turns out the arguments parser for the cli was coercing arguments to numbers when it could.
