### ISSUE TITLE
utf8 output type doesn't support inverting colors

### ISSUE THREAD

**Issue by TriMoon** [soldair/node-qrcode#185]
Using `qrcode -o qrtest.txt; cat qrtest.txt`

Seems the output type "utf8" is broken, because:
1. It does not change **white** and **black** squares using the `-d` and `-l` options. 
I tried to set one to `0000` and other to `ffff` and reverse but no change.
I even used diff to compare the 2 output versions
2. You get inverse output between terminal output and output to text file -> cat to terminal.
Perhaps related to #127 ?

**Comment by soldair** [comment]
I would be happy to support inverting the colors.

utf8 doesn't contain color information for the renderer, like ansii escapes do in terminals. Qrcode can't get this "right" for you because the result is just text. The user is expected to render it with the styles they feel like in a document etc.

**Comment by soldair** [comment]
landed in 1.4.0

**Comment by TriMoon** [comment]
Nice, just one problem not sure if its caused by this:
When you use the `-q` or `--qzone` option the ouput is bad...
```console
~/ qrcode -e L "http://www.local/" -d fff -o qrtest2.txt; cat qrtest2.txt 
saved qrcode to: qrtest2.txt

█████████████████████████████
█████████████████████████████
████ ▄▄▄▄▄ █▄█▄███ ▄▄▄▄▄ ████
████ █   █ █ ▀ ▄▀█ █   █ ████
████ █▄▄▄█ █▄ ▄ ▄█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄█▄█ █▄▄▄▄▄▄▄████
████ ▄ ▄█▀▄█ █ ██ ██   ▀ ████
████ █▀▀▄▀▄▄▀ ▄▀▀▄█ █ █ ▄████
█████▄█▄█▄▄█ █▄ ▀  █ ▄██▄████
████ ▄▄▄▄▄ ██ ▄▄▀▀▄█ ▀▀▀█████
████ █   █ █▀▄▀█ ▄█▄▄█▄█▄████
████ █▄▄▄█ █  █  ▄ ▄▀▀▄█▀████
████▄▄▄▄▄▄▄█▄█▄▄▄▄▄██▄▄██████
█████████████████████████████
```
Same with `-q 2` or anyother value >1
```console
~/ qrcode -e L "http://www.local/" -d fff -q 2 -o qrtest2.txt; cat qrtest2.txt
saved qrcode to: qrtest2.txt

█████████████████████████
21 ▄▄▄▄▄ █▄█▄███ ▄▄▄▄▄ 21
21 █   █ █ ▀ ▄▀█ █   █ 21
21 █▄▄▄█ █▄ ▄ ▄█ █▄▄▄█ 21
21▄▄▄▄▄▄▄█▄█▄█ █▄▄▄▄▄▄▄21
21 ▄ ▄█▀▄█ █ ██ ██   ▀ 21
21 █▀▀▄▀▄▄▀ ▄▀▀▄█ █ █ ▄21
21█▄█▄█▄▄█ █▄ ▀  █ ▄██▄21
21 ▄▄▄▄▄ ██ ▄▄▀▀▄█ ▀▀▀█21
21 █   █ █▀▄▀█ ▄█▄▄█▄█▄21
21 █▄▄▄█ █  █  ▄ ▄▀▀▄█▀21
21▄▄▄▄▄▄▄█▄█▄▄▄▄▄██▄▄██21
```

**Comment by soldair** [comment]
You're rather confused here.

You can't view utf8 codes in the terminal 
You need to render terminal codes which use escape sequences to draw them correctly. `qrcode hello` to save terminal codes to a file just arrow them in.

**Comment by TriMoon** [comment]
> I think we might be confused here.
> 
> You can't view utf8 codes in the terminal
> You need to render terminal codes which use escape sequences to draw them correctly. `qrcode hello` to save terminal codes to a file just arrow them in.

Viewing the file in a text editor, in my case atom-beta, shows same result...
I know that you can directly display in terminal using the terminal escape codes generated, but what we are talking here is the generated utf-8....which is still imho wrong...

**Comment by TriMoon** [comment]
imho, it's better to revert this change and re-implement using a logic that checks `if fg > bg` to decide characters to use. eg.:
  - `BB` or `WW`
  - `BW` or `WB`

**Comment by TriMoon** [comment]
Here is a piece of code that i just made to calculate luma of colors, **you** are free to use those functions in your decision flow to decide if you need to invert or not :wink:
Remove the `.txt` extension of the filename and make it executable to be able to run the nodejs code to see the output...
The interesting functions (for you) inside the file are:
  - `getRGBtriplet()` Get the RGB triplet from a CSS #hex string.
  - `lumaVal()` Get the luma value. (uses `getRGBtriplet()`)
  - The rest is just to make some automated output...

[test-getluma.mjs.txt](https://github.com/soldair/node-qrcode/files/3392876/test-getluma.mjs.txt)
