### ISSUE TITLE
Unwanted console logs

### ISSUE THREAD

**Issue by shilangyu** [soldair/node-qrcode#189]
## What happens
When running this small snippet: 
```js
require('qrcode').toString(`i_am_a_link`, { type: 'svg' })
```
I am getting a console log of: `text i_am_a_link` 

## What im expecting
No console logs, or a way to disable them

**Comment by soldair** [comment]
this should not be. ill take a look

**Comment by soldair** [comment]
fixed and published in 1.4.1. thanks for reporting!
