### ISSUE TITLE
Terminal output differs 

### ISSUE THREAD

**Issue by thmsnhl** [soldair/node-qrcode#191]
I just realised that the terminal output differs significantly when using `QRCode.toString` (from webpack plugin) in comparison to running `npx qrcode test` (directly in the terminal). 

**Expected behavior:**
Running `QRCode.toString('test', {}, function (err, string) {if (err) throw err console.log(string)})` leads to the same result as `npx qrcode test`

**Current behavior:**
Running `QRCode.toString('test', {}, function (err, string) {if (err) throw err console.log(string)})` renders: 

<img width="199" alt="Bildschirmfoto 2019-07-29 um 11 07 47" src="https://user-images.githubusercontent.com/5750821/62036058-59014180-b1f1-11e9-8965-a53b653d305a.png">

Running `npx qrcode test` renders: 

<img width="336" alt="Bildschirmfoto 2019-07-29 um 11 09 17" src="https://user-images.githubusercontent.com/5750821/62036076-60c0e600-b1f1-11e9-9396-eabe0d74d9db.png">

The QRCode from `npx` works fine, while the one rendered via `QRCode.toString` is not recognized.

**Comment by soldair** [comment]
hey. i would really like some help with documentation here =) you're not the first person to run into this and both of you have run into this very recently.

when you run `npx qrcode test` you're using the terminal renderer. 
https://github.com/soldair/node-qrcode/blob/master/lib/renderer/terminal.js

this is not the same as toString which outputs utf8 block characters 
https://github.com/soldair/node-qrcode/blob/master/lib/renderer/utf8.js

you could render this text really nicely with css correcting for `line-height` or in a google document if you like but it's just utf8 text. If you're rendering on the web it's almost certainly better to use svg or png data url as output.

```
QRCode.toDataURL('I am a pony!').then(console.log)
```

it looks like the documentation is wrong here https://github.com/soldair/node-qrcode#options-3 . it says that the default for toString should be an svg string not a utf8 string but here we are =)

```
QRCode.toString(text,{type:'svg'}).then(console.log)
```

**Comment by thmsnhl** [comment]
Hey @soldair thank you for the quick response and for clarifying this!

What I am trying to achieve is to use the terminal renderer to create a QRCode in my Webstorm terminal, so that I can quickly connect my smartphone to my machine.

How am I supposed to use the terminal renderer in this case?

**Comment by thmsnhl** [comment]
I found the solution by myself, thanks to your answer! 
```
        QRCode.toString('http://google.com',
        {
          type: 'terminal'
        }, function (err, string) {
          if (err) throw err
          console.log(string)
        })
```

Works just as expected. I didn't know that `"terminal"` was actually a valid option for `type` I will add this to the documentation, if this is fine for you?

**Comment by soldair** [comment]
oh good call. ill update the list of types.
