### ISSUE TITLE
DataURL is different in NodeJS and ReactJS

### ISSUE THREAD

**Issue by akalier170** [soldair/node-qrcode#194]
Hello. I use the toDataURL method to get image URL, then I set it as a src for an image in browser. I have my own .js file with this function:

```
const QRCode = require('qrcode');

export async function getQRCode(string) {
  return QRCode.toDataURL(string);
}
```

When I call this function from .jsx file with the string "Hello John Doe.", I get a 2378 characters long URL.

However, when I call exactly the same function from a Node.js file (as a part of a test for example), I get a URL that is only 1338 characters long and is very different from the first one.

The result images (from both of these URLs) look the same though, also they both contain the "Hello John Doe." string. But they are of different sizes.

![twoPics](https://user-images.githubusercontent.com/54033680/62924175-d90dd680-bdaf-11e9-876d-6f4590ffe5e7.png)

How is this possible? How can I get the same result?

**Comment by soldair** [comment]
a data url is a png. In the browser we generate the url with a canvas tag.  Server side in node.js we use pngjs. It looks like the browser users different quality settings/compression settings and is likely outside of our control.

might i suggest you use svg? `console.log(await QRCode.toString('hello john doe',{type:'svg'}))`
or you can render it directly to a canvas and play around with more efficient serialization there.
