### ISSUE TITLE
How to save QR code image on cloudinary or AWS when deployed on heroku? 

### ISSUE THREAD

**Issue by 2u4u** [soldair/node-qrcode#198]
I was using `toFile` to save QR code image on local machine. Now I deployed project on heroku. How can I save image on cloudinary or AWS?   

```
QRCode.toFile(`public/user/${handle}.png`, URL, {}, (err) => {
    if (err) throw err
    console.log('qr code created')
  })
```

**Comment by soldair** [comment]
you should be able to use the client documentation for the cloud service you want to use and upload the file you created.

it's possible to avoid creating an actual file altogether and save just the data as a buffer with most cloud apis. if you want to do this you would use method `QRCode.toBuffer('my code',console.log)` it doesn't seem documented which is a  mistake.
