### ISSUE TITLE
CLI -v tag unexpected behaviour

### ISSUE THREAD

**Issue by kennedybaird** [soldair/node-qrcode#201]
Docs suggest that when using the `-v` tag that you'll be able to define the version number of QR Code to be generated.

Readme.md states:

```
QR Code options:
  -v, --version  QR Code symbol version (1 - 40)
```

However CLI returns the following from `qrcode -h`

```
QR Code options:
  -v, --version  Show version number                                   [boolean]
```

Running `qrcode -v 20 -o test.svg 'testcontent'` outputs the version number of the CLI, as opposed to being able to define the QR code of the version (which I would expect, and as the Readme indicates).

How can we use the CLI to render specific QR versions?

**Comment by soldair** [comment]
oh that's very strange.

it seems this yargs version is intercepting and is not allowing the -v flag to mean anything but the version of the package itself.

qr versions are normally dynamically computed based on the input text size so its not often folks want to specify them i guess =). It's very useful for limiting the text that can be in a qr code and for generating qr codes with always the same number of points so i get why you might want it.

**Comment by soldair** [comment]
released in patch as v1.4.2

**Comment by kennedybaird** [comment]
Great, that is what I was going to suggest.

However, it doesn't seem to be modifying the output of the QR code, even with the `-qv` tag with different values.

It's the same each time

**Comment by kennedybaird** [comment]
Ok, so i can't find any examples on the internet of yargs accepting multi-letter options.

In dev environment when I changed the option from `qv` to `G` or `x` AND changed the `parseOptions` function to look for `qversion` it worked.

**Comment by kennedybaird** [comment]
Actually, seems that `-v` does work, error was in line 30 of `/bin/qrcode`
