### ISSUE TITLE
node.js

### ISSUE THREAD

**Issue by moorecashflow** [soldair/node-qrcode#206]
New to coding and I am using wix. I downloaded the qr code node but I am not sure what to do next. Think you help? and what's the pony part?

**Comment by soldair** [comment]
i appreciate that you asked for help and that you're new to coding. you have a fun time ahead of you.
In the readme, the pony part is the text you want to put into the qrcode.

if you want to use this program to make qrcode image files or text files like svg to show on a website you should do that. If you want to use it in the browser someone recently contributed an updated example page https://vicjohnson1213.github.io/node-qrcode/

you can view source on that to learn things if you like.

in nodejs you npm install qrcode. if you need help using nodejs or npm you should google those terms or take a look at nodejs.org.

good luck.

**Comment by moorecashflow** [comment]
Okay thank you
