### ISSUE TITLE
Possible encoding bug with binary data

### ISSUE THREAD

**Issue by benallfree** [soldair/node-qrcode#207]
Thanks for the great library! I think I encountered a bug, or maybe just a point of clarity:

It looks like `QRCode.toFile` expects only `string` data. Likewise, the TypeScript definitions support this. Even a segment expects `string` data.

For my use case, I have a `Buffer` of gzipped data, so it's binary. Converting it using `Buffer.toString()` won't work because it creates additional bytes due to whatever string encoding I choose. Internally, when the library converts it back to a `Buffer` for processing, it is altered. 

I noticed that it actually *will* work to pass a buffer in as a segment like `{data: someBuf, mode: 'byte'}`, but the instructions and the TypeScript definitions don't actually support that.

Does not work:

```
const data = Buffer.from([255,255,255])
QRCode.toFile(
         'foo.png',
          data.toString('utf8'),
          ...options...,
          ...callback...
        )
```

Does work:

```
const data = Buffer.from([255,255,255])
QRCode.toFile(
         'foo.png',
          [{ data, mode: 'byte' }],
          ...options...,
          ...callback...
        )
```

Maybe I'm just not thinking clearly, but it seems that non-string data such as byte arrays and buffers should be 1st class citizens. If you agree, I'd be open to discussing a PR and shooting something over.

**Comment by soldair** [comment]
i totally agree. i'm interested in your proposal =)

there are issues depending on the types because of the lack of buffer in the browser and things like that.

**Comment by benallfree** [comment]
Awesome. I think I want to reach out to whoever maintains @types/qrcode as well because I'm using TypeScript and it drove me crazy because it wouldn't accept a Buffer in type checking. I had to go through your code to make sure a Buffer would actually work (`Buffer.from(someBuffer)` does work) first.

What about the `Uint8ClampedArray` you're using elsewhere? It's easy enough to get from a `Buffer` to a `Uint8ClampedArray`. We could even do a little internal conversion.

**Comment by soldair** [comment]
i use typescript daily and im afraid of manually authoered types in general.
At some point i'd accept a rewrite of qrcode in ts just to not have users go through that.

for now i'd any it up or require it and type the interface you use in your app even though it's ugly.

**Comment by soldair** [comment]
well thinking more. we cant just transparently support binary data because its a special type in qr code world. it makes a different type of qrcode code that holds less data.
stil,l interested in where you end up tho

**Comment by benallfree** [comment]
A ts rewrite sounds like deep water... 

So come to think of it, since `core/byte-data.js` uses `Buffer`, how would BYTE segments even work in the browser? 

Let me know where you think is the best place to begin. For now maybe just a readme clarification that passing a buffer or clamped array to a byte segment will work?

**Comment by soldair** [comment]
i like this. at least your hard won work around will be put to good use for other folks

**Comment by benallfree** [comment]
If generating QRs in the browser is a priority, maybe https://github.com/feross/buffer is needed? Am  I correct that anything in your lib using  `Buffer` will fail in the browser?

#208 while it's fresh in my mind :)

**Comment by soldair** [comment]
its not correct. because we have a buffer polyfill that predates feross' one.
we have a big problem because in some cases its used server side nad its created a big issue removing calls to `new Buffer`
