### ISSUE TITLE
Calculate the grid size

### ISSUE THREAD

**Issue by bitttttten** [soldair/node-qrcode#213]
Is there a way to find out how many rows and columns it has been generated with?

I wanted to hide some of the middle squares to make a little pattern, like removing 10 squares from the middle in a certain way, and it would be easy to do if I knew how many rows and columns are present so then I would know the size of the grid :)

**Comment by soldair** [comment]
the number of modules i determined by the amount of data you put into the qrcode.
the default is we auto pick a "qrcode version" based on your encoding type and the number of bytes you want to encode.

you may find this is easier to do with just image manipulation in canvas rather that changing the "modules" squares.

https://github.com/soldair/node-qrcode#qr-code-capacity

if you want a code to be the same size every time you can provide a version and error correction level and it'll be the same size every time.
