### ISSUE TITLE
ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by anuj9196** [soldair/node-qrcode#215]
I'm trying to get it to work in **Angular 8**.

In the `component.ts` file
```
import QRCode from 'qrcode`;

export class MyComponent implements OnInit {
    ngOnInit() {
        const canvas = document.getElementById('canvas');
        QRCode.toCanvas(canvas, 'Hello World', (res) => {
            console.log('res: ', res);
         });
    }
}
```

But this is giving an error:

```
ReferenceError: Buffer is not defined
    at ReedSolomonEncoder.encode (reed-solomon-encoder.js:37)
    at createCodewords (qrcode.js:340)
    at createData (qrcode.js:286)
    at createSymbol (qrcode.js:424)
    at Object.create (qrcode.js:498)
    at browser.js:53
    at new ZoneAwarePromise (polyfills.js:3725)
    at renderCanvas (browser.js:51)
```

**Comment by lyxia** [comment]
+1

**Comment by soldair** [comment]
thanks I just released a version yesterday that probably introduced this.
ill take a look now

**Comment by anuj9196** [comment]
@soldair Thanks. It's working now.

**Comment by davidknoll** [comment]
@soldair I've just found this issue and I'm experiencing it or something similar on 1.2.2, 1.3.4, 1.4.0-1.4.4, and master at eb2d499. I'm using AngularJS 1.5.8, with qrcode in the frontend/browser, and the error appears in the browser debug console. On some versions of qrcode the root component of my app won't instantiate, on some it only triggers once I try to use it.

**Comment by plumpNation** [comment]
If anyone is coming here from a rollup project, https://www.npmjs.com/package/rollup-plugin-node-builtins

**Comment by james-innes** [comment]
As per this [discussion](https://github.com/rollup/rollup/issues/2881) around **node-globals/node-builtins** I found [rollup-plugin-node-polyfills](https://github.com/ionic-team/rollup-plugin-node-polyfills) got the QR code working for me using Rollup with Svelte.
