### ISSUE TITLE
 process.dlopen(filename, module.exports);

### ISSUE THREAD

**Issue by peterbarretto** [soldair/node-qrcode#22]
module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: The specified module could not be found.

How do i fix this??

**Comment by DeoLeung** [comment]
I ran into the same problem using node v4.2.2, same as I installed it globally.

$ npm install -save qrcode
npm http GET https://registry.npmjs.org/qrcode
npm http 304 https://registry.npmjs.org/qrcode
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/canvas
npm http GET https://registry.npmjs.org/bops/0.0.6
npm http 304 https://registry.npmjs.org/canvas
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/bops/0.0.6
npm http GET https://registry.npmjs.org/base64-js/0.0.2
npm http GET https://registry.npmjs.org/to-utf8/0.0.1
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> canvas@1.3.5 install /somewhere/canvas
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/base64-js/0.0.2
make: Entering directory `/somewhere/node_modules/canvas/build'
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node
  SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node: Finished
  COPY Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
npm http 304 https://registry.npmjs.org/to-utf8/0.0.1
  CXX(target) Release/obj.target/canvas/src/CanvasGradient.o
  CXX(target) Release/obj.target/canvas/src/CanvasPattern.o
  CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o
  CXX(target) Release/obj.target/canvas/src/color.o
  CXX(target) Release/obj.target/canvas/src/Image.o
  CXX(target) Release/obj.target/canvas/src/ImageData.o
  CXX(target) Release/obj.target/canvas/src/init.o
  CXX(target) Release/obj.target/canvas/src/FontFace.o
  SOLINK_MODULE(target) Release/obj.target/canvas.node
  SOLINK_MODULE(target) Release/obj.target/canvas.node: Finished
  COPY Release/canvas.node
make: Leaving directory `/somewhere/node_modules/qrcode/node_modules/canvas/build'
qrcode@0.4.2 node_modules/qrcode
├── colors@1.1.2
├── bops@0.0.6 (to-utf8@0.0.1, base64-js@0.0.2)
└── canvas@1.3.5 (nan@2.1.0)

$ qrcode hi
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/qrcode/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by Subomi** [comment]
This is still an issue yet unsolved?

**Comment by soldair** [comment]
This is an error folks can get if they have an issue with native modules. This is not really a qrcode issue unless i need to bump the version of canvas. if you are having the problem let me know :)

**Comment by laggingreflex** [comment]
As per [this comment](https://github.com/nodejs/node/issues/2964#issuecomment-152210141) could you guys try running the [dependencywalker](http://dependencywalker.com) on whatever `.node` file that's causing the error, like `node_modules\canvas\build\Release\canvas.node` 

I was similarly missing LIBEAY32.DLL in scrypt.node (a different module than node-qrcode altogether)
![](http://i.imgur.com/O0Boke8.png)
which comes from installing OpenSSL and that fixed the issue for me.

**Comment by soldair** [comment]
very helpful thanks @laggingreflex !

**Comment by Akiiki** [comment]
I had the same Issue so I did `npm rebuild`   then `sudo npm install -g ethereumjs-testrpc`

**Comment by ogbiyoyosky** [comment]
Just had the same problem.
solution: I deleted the node_modules,and run `npm install`.
Note: Make sure the package.json is intact.
