### ISSUE TITLE
Fatal Error on function toCanvas

### ISSUE THREAD

**Issue by rogeriojlle** [soldair/node-qrcode#223]
Steps to reproduce:
`Welcome to Node.js v13.6.0.
Type ".help" for more information.
> const { createCanvas } = require('canvas')
undefined
> const { toCanvas } = require('qrcode')
undefined
> let _qr = createCanvas()
undefined
> toCanvas(_qr,'\n')

<--- Last few GCs --->

[6725:0x6290940]    86708 ms: Mark-sweep 3.6 (6.2) -> 3.6 (6.0) MB, 2.6 / 0.0 ms  (average mu = 1.000, current mu = 0.012) external memory pressure GC in old space requested
[6725:0x6290940]    86710 ms: Mark-sweep 3.6 (6.0) -> 3.4 (6.0) MB, 2.0 / 0.0 ms  (average mu = 1.000, current mu = 0.005) external memory pressure GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x280cb37c0921 <JSObject>
    0: builtin exit frame: createImageData(this=0x045e2a186361 <CanvasRenderingContext2D map = 0x1df383eaa61>,116,116,0x045e2a186361 <CanvasRenderingContext2D map = 0x1df383eaa61>)

    1: render [0xf08efc95c81] [/home/rogerio/projetos/nextjs/apps/etiquetas/node_modules/qrcode/lib/renderer/canvas.js:38] [bytecode=0x45e2a1839b9 offset=112](this=0x2d5a821c01f1 <JSGlobal Object>,0x045e2a185f81 <Obj...

FATAL ERROR: v8::ArrayBuffer::New Allocation failed - process out of memory
 1: 0xa9d200 node::Abort() [node]
 2: 0xa9f4c2 node::OnFatalError(char const*, char const*) [node]
 3: 0xc06ffe v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xc07379 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xc0745b  [node]
 6: 0xc24555  [node]
 7: 0x7fad143acc7c Context2d::CreateImageData(Nan::FunctionCallbackInfo<v8::Value> const&) [/home/rogerio/projetos/nextjs/apps/etiquetas/node_modules/canvas/build/Release/canvas.node]
 8: 0x7fad143a3339  [/home/rogerio/projetos/nextjs/apps/etiquetas/node_modules/canvas/build/Release/canvas.node]
 9: 0xc73f5c  [node]
10: 0xc75d67 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x145c4b9  [node]
Abortado (imagem do núcleo gravada)
`

**Comment by soldair** [comment]
it may be that your canvas was compiled with another node.js version or the native module canvas that i depend on doesn't support version 13 yet.
try `npm rebuild` and run the file again?

Right now this package only depends on canvas as a development dependency. There is no reason why you should hit this as a consumer of the library unless you are using server side canvas independently of qrcode.

If you're developing qrcode and find a fix for this that would be a good contribution to pr.

please reopen if there is any more information you can provide about how you are using qrcode and it's something we can fix. A minimal reproduction and install instructions would be appreciated.
