### ISSUE TITLE
typescript build error 'Cannot find name 'HTMLCanvasElement'' on node serverside

### ISSUE THREAD

**Issue by Digitum** [soldair/node-qrcode#225]
Qrcode version: 1.4.4
Environment: Docker node:12
Using @types/qrcode

Code:
```typescript
import QRCode from 'qrcode'
let graphics = await QRCode.toString('somedata', {type: 'svg', margin: 0})        
```

Package file dependencies:
```
{
    "@types/qrcode": "^1.3.4",
    "qrcode": "^1.4.4"
}
```

Tsconfig compilerOptions:
```json
{
	"target": "es6" 
	"module": "commonjs" 
	"lib": ["es2019"],
	"sourceMap": true,
	"outDir": "dist",
	"strict": true,
	"noImplicitAny": true,
	"moduleResolution": "node",
	"baseUrl": "./",
	"paths": {
		"*": [
			"node_modules/*",
			"src/types/*",
			"src/config/*"
		]
	},
	"esModuleInterop": true,
	"resolveJsonModule": true
}
```
Get several errors like:
```
node_modules/@types/qrcode/index.d.ts(163,41): error TS2304: Cannot find name 'HTMLCanvasElement'.
node_modules/@types/qrcode/index.d.ts(167,41): error TS2304: Cannot find name 'HTMLCanvasElement'.
node_modules/@types/qrcode/index.d.ts(171,41): error TS2304: Cannot find name 'HTMLCanvasElement'.
node_modules/@types/qrcode/index.d.ts(175,91): error TS2304: Cannot find name 'HTMLCanvasElement'.
node_modules/@types/qrcode/index.d.ts(183,124): error TS2304: Cannot find name 'HTMLCanvasElement'.
node_modules/@types/qrcode/index.d.ts(200,42): error TS2304: Cannot find name 'HTMLCanvasElement'.
node_modules/@types/qrcode/index.d.ts(204,42): error TS2304: Cannot find name 'HTMLCanvasElement'.
node_modules/@types/qrcode/index.d.ts(208,42): error TS2304: Cannot find name 'HTMLCanvasElement'.
```
when run `tsc`

Does not know if this is a issue in `@types/qrcode` or in `qrcode` package.
Temporary solution, but not optimal, is to add following to compilerOptions: `"skipLibCheck": true`

Can this be solved by actually include typescript support in package if issue is in `@types/qrcode` package?

**Comment by soldair** [comment]
this would be in the @types/qrcode package. this library supports both browsers and servers so i can see why they would find it tricky.

you should probably declare a new global type just to get compilation to work  or include browser typings but that might cause more trouble than it's worth in the developer experience.

reopen if you feel i could answer this a bit better

**Comment by mikemaccana** [comment]
@fishcharlie Hello it's me, anyone else, I found the issue though searching and your solution worked for me too. Oddly it was also the `qrcode` library that caused it. Thanks!

**Comment by netkin-paris** [comment]
We tried the solution of @fishcharlie, but when our isomorphic lib was included in our frontend, it was conflicting with the native declaration of HTMLCanvasElement in lib.dom.d.ts

This declaration worked for us :   

```typescript
declare global {
  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  interface HTMLCanvasElement {}
}
```

**Comment by chandanky23** [comment]
Updating the `tsconfig.json` filename with the below changes worked for me.
```
{
    "compilerOptions": {
        "lib": [
            "es2016",
            "dom"
        ]
    }
}
```
