### ISSUE TITLE
not support browser IE9 IE10, do not use [Object.setPrototypeOf]

### ISSUE THREAD

**Issue by DemonCloud** [soldair/node-qrcode#227]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf

why use this api..

**Comment by DemonCloud** [comment]
@soldair 
the browser complete source in  qrcode/build/qrcode.min.js
use with Object.setPrototypeOf API, it only supports IE11,  but as you know,  IE9 support canvas right?

**Comment by soldair** [comment]
I'm not sure which module is using this. 
I'm happy to take a look if you provide a stack trace but i cant promise to be able to fix it.

In general would recommend using babel / webpack /etc to downlevel your javascript bundle to run in each browser you want to target. that way you can consume any library without worrying about new apis

feel free to reopen if you have more to add.

**Comment by DemonCloud** [comment]
@soldair 
build production qrcode.min.js path:  `node_modules/qrcode/build/qrcode.min.js`

the `qrcode.min.js` exist `Object.setPrototypeOf` API, this API is not work in IE9 IE10, will expect error.

you would try to replace this API for building scripts. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf

**Comment by DemonCloud** [comment]
@soldair 
in normally, webpack build production will not do compress with `node_modules`, sometimes
