### ISSUE TITLE
[Q] QR code as a 2D array

### ISSUE THREAD

**Issue by acagastya** [soldair/node-qrcode#246]
In the QR code's photo, some pixels are black (the set pixels) some are not. Is there an API, or a way which gives me a 2D-array of Booleans -- which pixels are set, which are not set?

**Comment by soldair** [comment]
yeah there is. i believe its getPixelArray or some such. should be in the docs

**Comment by soldair** [comment]
```
const code = require('qrcode').create(data,option)
```
and data is used like 
```
  const size = qr.modules.size
  const data = qr.modules.data
```

you can see more examples in lib/renderers

**Comment by acagastya** [comment]
`qr.modules.data` works like a charm.  Thanks, @soldair.  I will have to convert it to a 2D array though.
