### ISSUE TITLE
if create qrcode is a img，I want to set some attributes，eg: alt,title, can I do ?

### ISSUE THREAD

**Issue by baobinaqd** [soldair/node-qrcode#265]
if create qrcode is a img，I want to set some attributes，eg: alt,title, can I do ?

**Comment by soldair** [comment]
you can create whatever html you like passing the image as an src. =)
good luck. more info on https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img or perhaps https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API if you're using the canvas.
