### ISSUE TITLE
too large to scan in terminal

### ISSUE THREAD

**Issue by takayama-lily** [soldair/node-qrcode#271]
> qrcode.png 135x135 519bytes
![qrcode](https://user-images.githubusercontent.com/12014361/128352522-514c0e21-34d0-442e-8bfd-b3a37c61403c.png)
```js
qrcode.toString([{data:fs.readFileSync("qrcode.png")}], {type:"terminal"}).then(console.log)
```
windows10 powershell 1980x1080
![image](https://user-images.githubusercontent.com/12014361/128352866-b0ddf202-9025-4458-86b2-cb5af8b388df.png)

and I can not find any way to resize

**Comment by soldair** [comment]
You are putting the whole binary data of an image of a qr code in a qr code :sweat_smile: 

I would expect you to pass something like "hello i am data" to the "data" key rather then an image =)

In general qr codes have to be larger the more data they have in them. You can generate qrcodes with a specific output size limit by setting the version and error correction restricting the qrcode to an input size limit.

good luck.
