### ISSUE TITLE
Please create a new release/tag/build on npm 

### ISSUE THREAD

**Issue by obfuscatedgenerated** [soldair/node-qrcode#274]
The current release has a [vulnerability in yargs](https://app.snyk.io/test/npm/qrcode/1.4.4), however, the master branch is using a vuln free version of yargs.

Please update the package on npm to allow those without the necessary binaries to use the package.

Unless something is wrong on my end of course, so please look at this section of the error log I received when trying to install the package from git rather than the npm registry (by setting the version number to git+https://github.com/soldair/node-qrcode.git):
```
npm ERR! npm ERR! node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
npm ERR! npm ERR! node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
npm ERR! npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
npm ERR! npm ERR! node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@16.8.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v93-win32-unknown-x64.tar.gz
```

**Comment by obfuscatedgenerated** [comment]
I've observed that [a travis-ci build](https://travis-ci.org/github/soldair/node-qrcode/jobs/758045310) has failed with the same/similar error.

**Comment by soldair** [comment]
done
