### ISSUE TITLE
Can publish a  release version to NPM?

### ISSUE THREAD

**Issue by qqw78901** [soldair/node-qrcode#279]
Because the npm latest version is much behind the master.

Some features, such as ```--smaller```, are not included

**Comment by obfuscatedgenerated** [comment]
This should also resolve #274

**Comment by kareha** [comment]
> I'll take a look at this soon :)

What do you mean by "soon"? :)

**Comment by michens** [comment]
@kareha, see this comment from 18 months ago that also said "soon": https://github.com/soldair/node-qrcode/pull/226#issuecomment-624154625

**Comment by soldair** [comment]
1.5.0 published. try it out and let me know.
