### ISSUE TITLE
ansi-regex is vulnerable

### ISSUE THREAD

**Issue by madhav-vl** [soldair/node-qrcode#284]
Could you resolve security vulnerabilities related to [ansi-regex](https://www.npmjs.com/package/ansi-regex)

`$ npm audit`

**npm audit report**
ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix --force`
Will install qrcode@1.3.3, which is a breaking change
node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/strip-ansi
    cliui  4.0.0 - 5.0.0
    Depends on vulnerable versions of strip-ansi
    Depends on vulnerable versions of wrap-ansi
    node_modules/cliui
      yargs  10.1.0 - 15.0.0
      Depends on vulnerable versions of cliui
      Depends on vulnerable versions of string-width
      node_modules/yargs
        qrcode  >=1.3.4
        Depends on vulnerable versions of yargs
        node_modules/qrcode
    string-width  2.1.0 - 4.1.0
    Depends on vulnerable versions of strip-ansi
    node_modules/string-width
      wrap-ansi  3.0.0 - 6.1.0
      Depends on vulnerable versions of string-width
      Depends on vulnerable versions of strip-ansi
      node_modules/wrap-ansi

7 moderate severity vulnerabilities

**Comment by balazj** [comment]
There is already an open issue here: [https://github.com/soldair/node-qrcode/issues/278](https://github.com/soldair/node-qrcode/issues/278)

**Comment by soldair** [comment]
should be good with the new version
