### ISSUE TITLE
How to apply  custom styling to the QRCode 

### ISSUE THREAD

**Issue by rammohangowd** [soldair/node-qrcode#285]
I would like to apply some custom colors and also in middle of the QRCOde I want to add my image and apply some colors to the generated code. Are there any configurations available to apply styles? I am using this in my angular 11 application. If any examples would be helpful. Thank you!

**Comment by soldair** [comment]
You can use the canvas api or style with css on svg directly.
there are a number of questions about this just search in close dissues.
