### ISSUE TITLE
No minified file is generated

### ISSUE THREAD

**Issue by ZhangChengLin** [soldair/node-qrcode#286]
https://github.com/soldair/node-qrcode/releases/tag/v1.5.0

![Dingtalk_20211124131443](https://user-images.githubusercontent.com/30773389/143179371-7a5f3f0e-53e8-404f-bc14-cc41f281e50f.jpg)

![Dingtalk_20211124131505](https://user-images.githubusercontent.com/30773389/143179396-2855d734-ff8e-46f4-9fed-92a19b1fa1f9.jpg)

**Comment by soldair** [comment]
ah this is a breaking change and should be updated

**Comment by coeli** [comment]
precompiled bundles cannot be used in browser... minified files are not in /build/ and qrcode.js are not complete...
example : QRCode.toCanvas() issue...

Tested with old version of qrcode <1.5.0 with same issue when it worked before !
Do you have a solution ?

**Comment by t-balancin** [comment]
Hello team,

It would be really appreciated if minified files can be included with latest version. Thank you for work!

**Comment by soldair** [comment]
Not sure. You can build them by running the npm script on a git clone.
