### ISSUE TITLE
File not getting created

### ISSUE THREAD

**Issue by ag288** [soldair/node-qrcode#308]
I'm trying to use the qrcode package to generate a QR code and write it to a file. For this, I use the qrcode.toFile() api but unfortunately the file does not get created until after a very long time. Am I doing something wrong here? Following is my code:

`qrcode.toFile(
   path.join(__dirname,"images/filename.png"),
    "hello",
    {
      color: {
        dark: "#00F", // Blue dots
        light: "#0000", // Transparent background
      },
    },
    function (err) {
      if (err) throw err;
})`

**Comment by atrichkov** [comment]
I test your code with nodejs (v16.19.0 on linux) and it's working perfect.
So can you give more info about how you run it, what is your os, did you check permissions for images directory of your project ?

**Comment by soldair** [comment]
my guess is you are creating the file in an unexpected place or you are existing the program before the write is complete.
