### ISSUE TITLE
QRCode.toDataURL   error:You need to specify a canvas element

### ISSUE THREAD

**Issue by inprivacy** [soldair/node-qrcode#313]
version:1.5.1
uniapp 移动端

```

import QRCode from "qrcode";

codeUrl: ''
<img :src="codeUrl" />

let opts = {
                errorCorrectionLevel: 'H',
                type: 'image/png',
                quality: 0.3,
                margin: 1,
                color: {
                    dark: "#010599FF",
                    light: "#FFBF60FF"
                }
            }
let href = "https://fanyi.baidu.com/";
            QRCode.toDataURL(href, opts)
                .then(url => {
                    console.log(url)
                    this.codeUrl = url;
                })
                .catch(err => {
                    console.error(err)
                })


```

**Comment by soldair** [comment]
Im not sure how you're getting that error. let me know if you figure it out.

data urls do not require canvas as far as i recall

**Comment by uragecz** [comment]
@soldair i am having same issue, trying to use this app with react-native, and if i call toDataUrl i am getting same error about that i need to specify  canvas element

**Comment by bmovement** [comment]
Same error in Deno environment.

**Comment by NordlingDev** [comment]
The types lib is incorrect:

```ts
/**
 * Returns a Data URI containing a representation of the QR Code image.
 */
export function toDataURL(
    canvasElement: HTMLCanvasElement,
    text: string | QRCodeSegment[],
    callback: (error: Error | null | undefined, url: string) => void,
): void;
```

**Comment by DeepjyotiDeb** [comment]
I am also getting this same error. Any suggestions? (I am using it inside a web-worker)

**Comment by soldair** [comment]
Seems like you'll need to make an
https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas to draw to
or generate svg

**Comment by DeepjyotiDeb** [comment]
Thanks for replying! Could you give a rough outline for how i could implement with the QRCode library though?

**Comment by jingjingbushuijiao** [comment]
Has the problem been solved

**Comment by DeepjyotiDeb** [comment]
> Has the problem been solved
This is my work around for now, not sure how effecient it is though
`try {
    const canvas = new OffscreenCanvas(150, 150);
    QRCode.toCanvas(canvas, `${crypto.randomUUID().slice(0, 8)}`, function (error) {
      if (error) console.error(error);
    });
    const res = await canvas.convertToBlob();
    const newDataUrl = await blobToDataURL(res); //custom method for converting blobs to dataUrl
    return newDataUrl;
  } catch (err) {
    console.error('error in generateQR', err);
  }`

**Comment by evanoxu** [comment]
> version:1.5.1 uniapp 移动端
> 
> ```
> 
> import QRCode from "qrcode";
> 
> codeUrl: ''
> <img :src="codeUrl" />
> 
> let opts = {
>                 errorCorrectionLevel: 'H',
>                 type: 'image/png',
>                 quality: 0.3,
>                 margin: 1,
>                 color: {
>                     dark: "#010599FF",
>                     light: "#FFBF60FF"
>                 }
>             }
> let href = "https://fanyi.baidu.com/";
>             QRCode.toDataURL(href, opts)
>                 .then(url => {
>                     console.log(url)
>                     this.codeUrl = url;
>                 })
>                 .catch(err => {
>                     console.error(err)
>                 })
> ```

May be U can use:
 [uni.createOffscreenCanvas()](https://en.uniapp.dcloud.io/api/canvas/createOffscreenCanvas.html) as  OffscreenCanvas like this 

```
import QRCode from "qrcode";

const href = "https://fanyi.baidu.com/";

const opts = {
    margin: 1,
    width: 240,
    height: 240,
    errorCorrectionLevel: 'H',
};

const ocanvas = uni.createOffscreenCanvas({ type: '2d' });

QRCode.toDataURL(ocanvas, href, opts)
  .then(url => {
    console.log(url);
    this.codeUrl = url;
  })
  .catch(err => {
    console.error(err)
  })
```

I'm sure it's working. but it Only supported by WeChat Mini Program platform.
