### ISSUE TITLE
Update encode-utf8 to 2.0.0

### ISSUE THREAD

**Issue by tenjaa** [soldair/node-qrcode#316]
Hi,
looking at a quick license scan, I can see that encode-utf8 in version 1.0.3 does not provide any license information.
In 2.0.0 it does.
Would it be possible to update it?

Or maybe remove it even completely?

Would you be open to an PR?

**Comment by lennart-land** [comment]
Hi @soldair ,

this is currently a blocker for us and we really would like to use it. Could you please merge the corresponding PR or give some feedback?
Thanks!

**Comment by soldair** [comment]
done + qrcode@1.5.2
