### ISSUE TITLE
Small Render has bug

### ISSUE THREAD

**Issue by tofrankie** [soldair/node-qrcode#322]
Like this

<img width="1379" alt="iShot" src="https://user-images.githubusercontent.com/26947203/199734159-9efd6ebb-b9c3-4a23-a700-61c80e17ab2b.png">

**Comment by soldair** [comment]
This is related to terminals themselves. not the library.
if there is another qr code library that uses different tricks to render we'll accept a pull request to be more compatible with more terminals.

i believe this qr code will still work even with the lines on most readers. but this is also out of scope for the library
