### ISSUE TITLE
【React】Cannot read properties of undefined (reading 'getContext') 

### ISSUE THREAD

**Issue by weiwentao518** [soldair/node-qrcode#323]
**I am using the npm package QRCode in React framework and I get this error:**

`Cannot read properties of undefined (reading 'getContext')`

![image](https://user-images.githubusercontent.com/28976633/201295031-b7d17841-225e-435d-b0b2-f10d5196fd34.png)

![image](https://user-images.githubusercontent.com/28976633/201295073-d40d5189-f24a-41b8-8e98-814744fa7004.png)

how can i fix it??

**Comment by cpitul** [comment]
I think the library is not maintained anymore...

**Comment by weiwentao518** [comment]
> I think the package is not maintained anymore...

So what should I do, do I modify it myself after fork?

**Comment by goncaloflf** [comment]
Hey @weiwentao518 👋 
I had this issue, it probably means that you are passing the reference of the canvas to node-qrcode before it's initialized: double check if this is the case :)

**Comment by soldair** [comment]
yeah it seems like your canvas doesn't exist. this isn't related to the qrcode package.
