### ISSUE TITLE
Any way to change body shape of qrcode. like pixel types, square shapes or anything to customize it.

### ISSUE THREAD

**Issue by i-engy** [soldair/node-qrcode#329]
First of all thanks for this library. Great work. Its a feature request if you guys have bandwidth to do it or suggest a way.

is there any way to make this **qrcode** more **customizable** like change pixel size, shape, squares shape/size , use circles instead or similar. i see different types of **qrcodes**. 

Thanks in advance.

**Comment by soldair** [comment]
you can get the result as an array and render it on a canvas however you like.
it just has bits for if the square should be dark or not.
