### ISSUE TITLE
QR output to terminal can't be read by reader

### ISSUE THREAD

**Issue by WickyNilliams** [soldair/node-qrcode#33]
Should I be expecting better (read, higher fidelity) output than this? QR code reader isn't able to read the output:

![screen shot 2015-03-20 at 16 50 25](https://cloud.githubusercontent.com/assets/1091390/6756398/83d0f7dc-cf21-11e4-8fa1-891fdc65dfbc.png)

I can't tell if it's something related to my bash setup, or is this as expected?

**Comment by soldair** [comment]
it depends on your terminal configuration sadly. i had success in xfce term today with "hi" starting with my phone close and moving back until the scan was successful. 

![screenshot - 03222015 - 02 41 56 pm](https://cloud.githubusercontent.com/assets/119903/6771651/9c993f8c-d0a1-11e4-9b8b-5bf55677e650.png)

there must be modules on npm now that are better at drawing in the terminal than trying to use block characters. the big problem i ran into is that the 100% height block characters still leave a margin between lines which is colored the background color. 

when i wrote it it worked much better =). i would output them in selenium test build output so i could hijack the session cookies to deep dive a mobile site failure with one scan.
