### ISSUE TITLE
v1.5.2 breaks next.js build

### ISSUE THREAD

**Issue by oxcened** [soldair/node-qrcode#331]
Hey just wanted to give a heads up that the latest patch (v1.5.2) suddently broke my Next.js app pipeline, I figure others may face the same.
Seems like an issue with encode-utf8.

```
 Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/src/app/node_modules/encode-utf8/index.js
#10 74.85 require() of ES modules is not supported.
#10 74.85 require() of /usr/src/app/node_modules/encode-utf8/index.js from /usr/src/app/node_modules/qrcode/lib/core/byte-data.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
#10 74.85 Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/src/app/node_modules/encode-utf8/package.json.
#10 74.85 
#10 74.85     at new NodeError (internal/errors.js:322:7)
#10 74.85     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1131:13)
#10 74.85     at Module.load (internal/modules/cjs/loader.js:979:32)
#10 74.85     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
#10 74.85     at Module.require (internal/modules/cjs/loader.js:1003:19)
#10 74.85     at require (internal/modules/cjs/helpers.js:107:18)
#10 74.85     at Object.<anonymous> (/usr/src/app/node_modules/qrcode/lib/core/byte-data.js:1:20)
#10 74.85     at Module._compile (internal/modules/cjs/loader.js:1114:14)
#10 74.85     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
#10 74.85     at Module.load (internal/modules/cjs/loader.js:979:32) {
#10 74.85   code: 'ERR_REQUIRE_ESM'
#10 74.85 }
#10 74.85
```

For now I'm fixing qrcode's version in my package to v1.5.1 as I'm not sure how this could be managed.

**Comment by qcasey** [comment]
Also broke one of my apps, same error

**Comment by yonigoldberg** [comment]
Also broken for us and for our SDK users. 

@soldair - this might be related to: https://github.com/soldair/node-qrcode/commit/dbbb46da8bdbbba38fcf368ed733ae81240dfd3f

Any chance to revert and release a v.1.5.3 release to mmitigate for now?

**Comment by NormandoHall** [comment]
Also broken sveltekit (vitejs)

**Comment by NormandoHall** [comment]
https://github.com/LinusU/encode-utf8/releases/tag/v2.0.0

💥 Breaking Changes
Convert package to ESM

Migration Guide:

This relases changes the package from a Common JS module to an EcmaScript module, and drops support for older versions of Node.

The minimum version of Node.js supported is now: 12.20.0, 14.13.1, and 16.0.0
The package must now be imported using the native import syntax instead of with require

**Comment by firrae** [comment]
This is the problem LOC: https://github.com/soldair/node-qrcode/blob/dc20f975a59664cc78c477507663b57b66cc2854/lib/core/byte-data.js#L1

The solution is to properly handle ESM like someone tried to promote in #241, but that seems dead now. This has completely broken our application.

**Comment by soldair** [comment]
resolved
