### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by angelmultivende** [soldair/node-qrcode#332]
Hi we are using qrcode "1.5.0" and apparently this change (https://github.com/soldair/node-qrcode/commit/dbbb46da8bdbbba38fcf368ed733ae81240dfd3f) is causing this error: "
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/tychus/Documents/multivende/main-dev/node_modules/encode-utf8/index.js from /Users/tychus/Documents/multivende/main-dev/node_modules/qrcode/lib/core/byte-data.js not supported.
Instead change the require of index.js in /Users/tychus/Documents/multivende/main-dev/node_modules/qrcode/lib/core/byte-data.js to a dynamic import() which is available in all CommonJS modules.
" our node version is "16.17.0".

**Comment by zeeoneofficial** [comment]
![IMG_20230422_113002](https://user-images.githubusercontent.com/92008777/233759783-43fa6854-e560-4e83-81a1-c28987313a77.jpg)

Try changing your qr code version, like mine

**Comment by KAWATAAAAAA** [comment]
When you are making a destructive upgrade, you should not modify the z version in the x.y.z version. Currently, I am definitely not the only one encountering this issue，  BTW ， the upstairs brother's method is effective

**Comment by janneman001** [comment]
same issue here. breaks the ci e2e test of the application

**Comment by utibeabasi6** [comment]
anyone have a fix? im experiencing this too

**Comment by soldair** [comment]
reverted.

**Comment by janneman001** [comment]
thanks. works again here.
