### ISSUE TITLE
errorCorrectLevel medium as max

### ISSUE THREAD

**Issue by yagop** [soldair/node-qrcode#36]
I've been testing and it seems that generating QR with `medium` as `errorCorrectLevel` option results in `H` error correction level in state of `M`.

```js
var QRCode = require('qrcode');
var opts = {errorCorrectLevel: "medium"};
QRCode.save('qr.png', 'foo', opts);
```

![qr](https://cloud.githubusercontent.com/assets/5002453/8149394/e183655c-12c1-11e5-8d13-7e0e82d5dfbf.png)

**Comment by soldair** [comment]
this is strange. it gets translated to string "M" here https://github.com/soldair/node-qrcode/blob/master/qrcode.js#L48

and that key is eventually translated to https://github.com/soldair/node-qrcode/blob/master/lib/qrcode-draw.js#L184

but guess what. the value of medium error correction is 0 to it must fall back to the default of "H" lol
