### ISSUE TITLE
publish a new version to npm

### ISSUE THREAD

**Issue by tacman** [soldair/node-qrcode#363]
https://www.npmjs.com/package/qrcode

Looks like the last time it was published was a year ago.  #317 isn't reflected, so it's throwing a warning about it.

**Comment by subvertallchris** [comment]
+1, @soldair mind publishing a new version?

**Comment by soldair** [comment]
seems like we can get this sorted =) let ya know

**Comment by soldair** [comment]
+ qrcode@1.5.4

not sure if this fixed the issue because we didnt have many unmerged changes.
re open if you still need a hand.,

**Comment by anisabboud** [comment]
The new version is still missing the `build` folder (which existed up to version `1.5.1` and is missing in `1.5.2`, `1.5.3`, `1.5.4`).

- https://github.com/soldair/node-qrcode/issues/333
- https://github.com/soldair/node-qrcode/issues/335
- https://github.com/soldair/node-qrcode/issues/346
- https://github.com/soldair/node-qrcode/issues/355
- https://github.com/soldair/node-qrcode/issues/362

**Comment by CuAnnan** [comment]
@soldair Could you reopen this so that we know what the state of play is with the built browser versions and/or CDNs?

Could really use that front end javascript.
