### ISSUE TITLE
Adjustable QR code image size

### ISSUE THREAD

**Issue by tixelated** [soldair/node-qrcode#4]
Hi - would love to help make QR code image sizes configurable at run time, any pointers?

**Comment by vigreco** [comment]
I think this has been solved in latest releases 👍

**Comment by gabzim** [comment]
I need to generate qr codes of 512x512, how was this solved? there's no info on this

**Comment by soldair** [comment]
@gabzim 
look like you can pass `width` and `height` in `options` if you set the type to be png to any function that makes a png file.

toDataURL toFile toFileStream

this should totally be documented. sorry friend.

https://github.com/soldair/node-qrcode/blob/master/lib/renderer/png.js#L10

**Comment by gabzim** [comment]
@soldair thanks for the info and speed! much appreciated!
