### ISSUE TITLE
Installation section issue

### ISSUE THREAD

**Issue by fatelei** [soldair/node-qrcode#40]
When build node-qrcode, it need `libgif-dev`. But the doc doesn't mention it.

Change:

```
sudo apt-get install libpixman-1-dev libcairo2-dev libpangocairo-1.0-0 libpango1.0-dev
```

To:

```
sudo apt-get install libpixman-1-dev libcairo2-dev libpangocairo-1.0-0 libpango1.0-dev libgif-dev
```

**Comment by soldair** [comment]
geat would you mind opening a pull request? you can just click edit on the readme through the web ui =)
