### ISSUE TITLE
unable to install without jpeglib-dev on ubuntu

### ISSUE THREAD

**Issue by organismen** [soldair/node-qrcode#46]
Thanks for a good package, I followed your instructions: 

sudo apt-get install libpixman-1-dev libcairo2-dev libpangocairo-1.0-0 libpango1.0-dev libgif-dev

I didnt got it to work before I realized that I needed to install the libjpeg-dev package. 

Maybe I didnt do it right the first time but I maybe this info helps someone else!

**Comment by soldair** [comment]
ok great. its a moving target for a library thats been around for 5 or so years. I'll add it to the readme.
