### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by skgitter** [soldair/node-qrcode#48]
I got this npm, decided to use it. But when I install, it gives error

Can anyone please help me out ?

### Error log 

![error](https://cloud.githubusercontent.com/assets/8007683/16608530/69fca2d4-436a-11e6-80ab-d24589f11264.png)

**Comment by newpanjing** [comment]
pyton not supported by gyp

**Comment by soldair** [comment]
looks like your build environment for native modules is not setup.

we depend on node canvas. so these build instaurction may help you run this on windows https://github.com/Automattic/node-canvas/wiki/Installation---Windows

**Comment by soldair** [comment]
this really amazing moule may be the easiest way to setup your windows build environment 
https://www.npmjs.com/package/windows-build-tools
