### ISSUE TITLE
Adjust QRCode

### ISSUE THREAD

**Issue by dannyto** [soldair/node-qrcode#52]
Hi Soldair!

Can this module allow to adjust the square of qrcode. When the data is big the square look so small

![qrcode](https://cloud.githubusercontent.com/assets/13778373/17963910/d75f1a8e-6ae1-11e6-9c38-8fc842fa54ab.png)

![qrcode](https://cloud.githubusercontent.com/assets/13778373/17963976/10199c32-6ae2-11e6-8346-8ac40950b27f.png)

Thankz,

**Comment by soldair** [comment]
the size of the anchor point (in the red square you added to the second image)  relative to the size of the smaller square is a fixed ratio required by the qr code reader to figure out how to read it.

as far as i know we cannot adjust the size of the anchor squares without reducing the success rate for scanners.

you can make the code draw squares or "modules" with more pixels by setting the scale option to a larger value. it defaults to 4.

something like this... (untested)
```js
var qrcode = require('qrcode')
qrcode.toDataURL('scale test',{scale:10,errorCorrectLevel:"minimum"},function(err,dataURL){
   console.log(dataURL)
})
```

the default error correction should be maximum. if you want smaller codes you can remove some error correction. using the errorCorrectLevel option above

**Comment by dannyto** [comment]
Thankz
