### ISSUE TITLE
Having an issue installing it?

### ISSUE THREAD

**Issue by rstudner** [soldair/node-qrcode#57]
npm install --save node-qrcode

It hangs(?) on the loading webDrivers step.  

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

> node-browser@0.0.3 install /Users/rstudner/projects/auth-api/node_modules/node-browser
> node ./build.js

load: download webDrivers...
```

**Comment by soldair** [comment]
would you try installing this in an empty project there may be an issue with your other dependencies.

**Comment by rstudner** [comment]
```
mkdir foo
cd foo
npm install node-qrcode --save
```

that hangs on the load: download webDrivers

i'm on OSX btw (minor detail I should have mentioned at the start).

**Comment by soldair** [comment]
k ill try on node 6. i only have linux but ill let you know if i can repro
did you `npm init` inside foo? it's ambiguous where it'll be saving if there no package.json inside foo

**Comment by rstudner** [comment]
I did an npm init, sorry for leaving that out.

**Comment by soldair** [comment]
ok. build.js in node-qrcode is only run on publish never part of install so it cannot possibly be hanging there.

the only suggestion i have is to install verbose
`npm install --verbose`

and maybe share the npm-debug.log after waiting for the command to timeout.

**Comment by rstudner** [comment]
```
npm info lifecycle node-browser@0.0.3~install: node-browser@0.0.3

> node-browser@0.0.3 install /Users/rstudner/git/foo/node_modules/node-browser
> node ./build.js

load: download webDrivers...
```

Not sure if I wait forever if it will actually timeout.  But here we go :)

**Comment by soldair** [comment]
you see node-browser is not a dependency of qrcode.

how is this module getting installed!

**Comment by vigreco** [comment]
@rstudner on NPM the package name is **qrcode**, not node-qrcode :)
Look [here](https://github.com/soldair/node-qrcode#installation).
Try with `npm install qrcode`

**Comment by soldair** [comment]
lol thanks @vigreco

**Comment by rstudner** [comment]
Oh my lord.

I'm so sorry everyone.  I tried so many qrcode libraries lah lah.

**Comment by rstudner** [comment]
And whatever it is worth, I was using https://github.com/alexeyten/qr-image in the meantime.

I'll compare/contrast the two approaches.
