### ISSUE TITLE
maybe use jimp

### ISSUE THREAD

**Issue by soldair** [soldair/node-qrcode#58]
https://github.com/oliver-moran/jimp

this would remove our native dep to node-canvas to make png and jpegs. the canvas renderer should still wor but it'll need to require the canvas to be passed in.

just noting it here for later

**Comment by gajus** [comment]
@soldair In the mean time, can you make `canvas` an optional dependency?

I don't want to download it if I am not planning on generating PNG images.

**Comment by soldair** [comment]
@vigreco can we land https://github.com/soldair/node-qrcode/pull/67 yet?
@gajus this includes removing node canvas

**Comment by vigreco** [comment]
@soldair I think it's ready, we can merge it if it's ok for you too.

**Comment by soldair** [comment]
this has been released 0.8.0
