### ISSUE TITLE
qrcode.toCanvas with wrong

### ISSUE THREAD

**Issue by ngnono** [soldair/node-qrcode#72]
version ：0.8.1
my nodejs server on exec  qr.code.toCanvas(text,opts,cb) is wrong!!!!
this response :Error: You need to specify a canvas element

on [canvas.js](https://github.com/soldair/node-qrcode/blob/master/lib/renderer/canvas.js)  function getCanvasElement () 
on browser is ok
on server is not work
---
this code is

``` javascript
function getCanvasElement () {
  try {
    return document.createElement('canvas')
  } catch (e) {
    throw new Error('You need to specify a canvas element')
  }
}

```
change into

``` javascript
function getCanvasElement () {
  try {
   //check nodejs env
   if(module && module.exports){
      var Canvas = require('canvas');

      return new Canvas();
    }
    // browser env
    return document.createElement('canvas')
  } catch (e) {
    throw new Error('You need to specify a canvas element')
  }
}

```

**Comment by vigreco** [comment]
Hi @ngnono,
we've removed `node-canvas` dependency, to use canvas in node you need to specify a `node-canvas` instance as first parameter of [toCanvas](https://github.com/soldair/node-qrcode#tocanvascanvas-text-options-cberror) function.

```javascript
QRCode.toCanvas(new Canvas(), text, opts, function (err) {
})
```

**Comment by soldair** [comment]
@vigreco was this a breaking change or a docs issue?

**Comment by vigreco** [comment]
@soldair, neither of them I think.
`toCanvas` is part of new APIs and wasn't available before, so it cannot break code which use old versions.

However, I'll look into it to be sure.

**Comment by soldair** [comment]
great =) just curious

**Comment by ngnono** [comment]
okay.  :)
