### ISSUE TITLE
shasum check failed  ?

### ISSUE THREAD

**Issue by ankurmittal0562** [soldair/node-qrcode#87]
Performing application deployment (running for 2 hours 19 minutes).
Application deployment failed at 2017-08-28T05:25:30Z with exit status 1 and error: Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh failed.

+ /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm ERR! Linux 4.4.51-40.60.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.10.0-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.10.0-linux-x64/bin/npm" "--production" "install"
npm ERR! node v6.10.0
npm ERR! npm v3.10.10

npm ERR! shasum check failed for /tmp/npm-3202-82224c76/registry.npmjs.org/qrcode/-/qrcode-0.7.1.tgz
npm ERR! Expected: 732d5b53ffdd09de55e0dc6908746fd191fc6e53
npm ERR! Actual: 776015acae3d4d6680ab8cf12abf447baca774f8
npm ERR! From: https://registry.npmjs.org/qrcode/-/qrcode-0.7.1.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR! <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR! /tmp/deployment/application/npm-debug.log
Running npm install: /opt/elasticbeanstalk/node-install/node-v6.10.0-linux-x64/bin/npm
Setting npm config jobs to 1
npm config jobs set to 1
Running npm with --production flag
Failed to run npm install. Snapshot logs for more details.
Traceback (most recent call last):
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>
main()
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in main
node_version_manager.run_npm_install(options.app_path)
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_install
self.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))
File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_install
raise e
subprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v6.10.0-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status 1.
Incorrect application version "nodejs-3.0-c21d488-20170707-0222" (deployment 32). Expected version "nodejs-3.0-c21d488-20170828-0742" (deployment 35).
Instance ELB health state has been "OutOfService" for 2 hours 58 minutes: Instance has failed at least the UnhealthyThreshold number of health checks consecutively.

**Comment by ankurmittal0562** [comment]
can anyone please explain why we are getting this shashum check failed for qr code . the servers are in china aws

**Comment by soldair** [comment]
this should only happen if the download is corrupted in transit to you or the registry failed to send the correct bytes. it doesnt have anything to do with qrcode itself.

if you like you can email support@npmjs.com with the problem, and npm-debug.log, and the output of `npm version && npm config list`
