### ISSUE TITLE
toDataURL doesn't work in IE9

### ISSUE THREAD

**Issue by chenjigeng** [soldair/node-qrcode#91]
toDataURL doesn't work in IE9.
when I use it in IE9, the browser tell us that 'the object doesn't support “write”attributes or method'.Please check this problem.

**Comment by soldair** [comment]
im very interested in a fix for this please take a look at the stack trace and try to narrow it down. maybe share it here.
even better would be a pull request but let me know how far you get =)

**Comment by vigreco** [comment]
I think the issue is due to [this](https://github.com/soldair/node-qrcode/blob/master/lib/utils/typedarray-buffer.js#L52).
IE9 doesn't support `__proto__` therefore the `Uint8Array` instance isn't augmented with the extra methods like `write`, that generates the error.

**Comment by vigreco** [comment]
Hey @chenjigeng,
I've just pushed a [branch](https://github.com/soldair/node-qrcode/tree/fix/ie9) with a fix for this (hopefully).

Do you mind give it a try and tell us if it solves the issue?

**Comment by chenjigeng** [comment]
@vigreco 
hello,I had test it and it's ok.Thank you.

**Comment by vigreco** [comment]
awesome! thanks for the feedback.

**Comment by soldair** [comment]
wooo! :confetti_ball:

**Comment by chenjigeng** [comment]
ok,You are very good

**Comment by Puuuudding** [comment]
@soldair Since this fix comes after the release 0.9.0. Do you have any schedule about new release to make this fix available to npm?
