### ISSUE TITLE
Weird issue impact regarding String.bold() Javascript

### ISSUE THREAD

**Issue by renatograel14** [soldair/node-qrcode#93]
Hi everyone! 

This is really weird issue we've in our project...
Some places (in node.js) we use bold() to return some kind of HTML strings (I know this is a bad practice, by the way). 
The thing is:  when you require QRCode `.bold()` method stops working

You can test this usign node cli

```
$ node
> 'teste'.bold()
'<b>teste</b>'
> require('qrcode')
{ create: [Function: create],
  toCanvas: [Function: bound renderCanvas],
  toString: [Function: toString],
  toDataURL: [Function: toDataURL],
  toFile: [Function: toFile],
  toFileStream: [Function: toFileStream],
  drawText: [Function: toString],
  drawSvg: [Function],
  drawPNGStream: [Function: toFileStream],
  save: [Function: toFile],
  toDataURI: [Function: toDataURL] }
> 'teste'.bold()
TypeError: "teste".bold is not a function
    at repl:1:9
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)

```

I would like to know if is there any javascript method/property not supported

We already solve this by replacing .bold() by `<b> </b>` tag

Thanks!! 
Renato

**Comment by vigreco** [comment]
Hi Renato,
this is really strange.
There should be nothing in `qrcode` that interfere with `String`.

I tested your example with node v0.10, v4, v8, and it worked as expected:

```
$ node
> 'teste'.bold()
'<b>teste</b>'
> require('qrcode')
{ create: [Function: create],
  toCanvas: [Function: bound renderCanvas],
  toString: [Function: toString],
  toDataURL: [Function: toDataURL],
  toFile: [Function: toFile],
  toFileStream: [Function: toFileStream],
  drawText: [Function: toString],
  drawSvg: [Function],
  drawPNGStream: [Function: toFileStream],
  save: [Function: toFile],
  toDataURI: [Function: toDataURL] }
> 'teste'.bold()
'<b>teste</b>'
```
Which node and qrcode versions are you using?

**Comment by renatograel14** [comment]
HI, @vigreco, thanks for reply! 

I'm usung node v6.7.0 and qrcode@0.8.2

**Comment by vigreco** [comment]
Thanks for your feedback.
I think the issue is caused by `colors`, a dependency used in version `0.8.2`.
You should receive the same error using `require('colors')` in place of `require('qrcode')` in your example.

This dependency has been removed in version `0.9.0` so I think that the fastest fix would be updating `qrcode` to the latest version.
This would require no changes in your code.
