### ISSUE TITLE
Add support for reading text from stdin

### ISSUE THREAD

**Issue by adius** [soldair/node-qrcode#99]

**Comment by vigreco** [comment]
Hi @adius,
what's the use case of this?

**Comment by adius** [comment]
😳 

```$
qrcode < content.txt
contact 'James' | qrcode
```

I mean it's one of the most important features of Unix tools, that they support piping 😅

**Comment by vigreco** [comment]
ohh of course!
Don't know why but I thought you meant "interactive" input from stdin 😅 

Well, I think it would be a good feature to add in version `1.1.0`.
I'm about to release version `1.0.0`, so this will have to wait till the next release.

/cc @soldair

**Comment by soldair** [comment]
yeah good idea.
